fix: theme's token in the Button component
yamada-ui/yamada-ui pull request #1104
Opened 2024-03-30 01:54 UTC by mochi-sann

Closes #1081 

## Description
The button component has been modified to use style tokens.

## Current behavior (updates)

Style token not applied
## New behavior

Style tokens are applied
## Is this a breaking change (Yes/No): No

## Additional Information

2024-03-30 02:33 UTC, 108yen approved these changes

2024-03-30 02:44 UTC, 108yen requested changes
run `pnpm cangeset` and select `patch`

2024-04-01 01:09 UTC, mochi-sann commented
@108yen I ran `pnpm changeset` and select `patch`. Please review.

2024-04-01 01:15 UTC, 108yen requested changes

2024-04-01 01:15 UTC, 108yen commented on .changeset/green-plants-confess.md
> +"@yamada-ui/button": minor
Thank you!
Plese change to `patch`

2024-04-02 13:42 UTC, 108yen approved these changes

2024-04-02 16:17 UTC, merged