fix: apply theme's token to LoadingProvider component
yamada-ui/yamada-ui pull request #1108
Opened 2024-03-30 18:49 UTC by minagishl

Github issue #1100 

## Description

apply theme's token to LoadingProvider component

## Current behavior (updates)

no change

## New behavior

> Please describe the behavior or changes this PR adds

## Is this a breaking change (Yes/No):

## Additional Information

2024-03-30 19:19 UTC, taroj1205 requested changes
Thanks for your contribution!
Please include the `changeset` for the `patch`!

2024-03-31 05:32 UTC, minagishl commented
@taroj1205 
I ran `pnpm changeset`, please confirm.

2024-04-01 06:51 UTC, taroj1205 reviewed
Thanks! There are a few changes needed. Please fix it.

2024-04-01 06:51 UTC, taroj1205 commented on packages/components/loading/src/loading-provider.tsx
> +  zIndex: "fallback(full, 9999)",
`full` is not a token for zIndex. Please use `beerus` instead.

2024-04-01 06:51 UTC, taroj1205 commented on packages/components/loading/src/loading-provider.tsx
> +      zIndex: "fallback(full, 9999)",
`full` is not a token for `zIndex`. Please use `beerus`.

2024-04-01 06:55 UTC, minagishl commented
@taroj1205 
Corrected, please confirm.

2024-04-01 07:09 UTC, taroj1205 reviewed
LGTM

2024-04-01 07:10 UTC, taroj1205 approved these changes

2024-04-01 12:52 UTC, hirotomoyamada commented
Thanks!

2024-04-01 12:52 UTC, merged