🔧 chore(carousel): Update zIndex to use fallback value
yamada-ui/yamada-ui pull request #1164
Opened 2024-04-08 18:42 UTC by KekmaTime

Closes #1101

## Description
- Added support for utilizing theme tokens in the Carousel, CarouselIndicators, and CarouselControl components.

## Current behavior (updates)

- Styling values in components ignore theme tokens.
- Theme tokens are not utilized for styling which leads to inconsistency when themes are applied.

## New behavior

- Updated the components to utilize theme tokens for styling values.

## Is this a breaking change (Yes/No):

- Not sure yet

## Additional Information

I've made the CSS  calc function inside backticks so that it can be used in the JS/TS context

2024-04-12 04:17 UTC, komura-c requested changes
@KekmaTime 
Sorry for the late review. Please run `pnpm changeset` and select `patch`.

2024-04-12 11:32 UTC, KekmaTime commented
> Sorry for the late review. Please run `pnpm changeset` and select `patch`.
can you tell how what patch means? im new to using changeset 😅

2024-04-12 15:00 UTC, komura-c commented
@KekmaTime 
The patch means a version with backward compatible bug fixes in semantic versioning.
This will be used when the package is released and will be noted in related package's [`CHANGELOG.md`.](https://github.com/yamada-ui/yamada-ui/blob/main/packages/components/carousel/CHANGELOG.md#patch-changes-6)

2024-04-13 05:00 UTC, hirotomoyamada commented
@KekmaTime 

Hi, thanks for the PR.

In this PR, what you fixed is `@yamada-ui/carousel`. It looks like you are trying to upgrade the version of `@yamada-ui/react`. Also, this fix is probably a patch, not a major one.

So,

```
"@yamada-ui/react": major
```

to

```
"@yamada-ui/carousel": patch
```

2024-04-13 05:01 UTC, hirotomoyamada commented on .changeset/dull-pumpkins-love.md
> +"@yamada-ui/react": major
Change `"@yamada-ui/carousel": patch`

2024-04-14 19:14 UTC, hirotomoyamada approved these changes

2024-04-17 13:05 UTC, komura-c approved these changes
Approved

2024-04-17 13:22 UTC, merged