docs(portal): add component documentation
yamada-ui/yamada-ui pull request #1228
Opened 2024-04-18 22:04 UTC by KekmaTime

Closes https://github.com/yamada-ui/yamada-ui/issues/1220 

## Description

JSDoc is  missing from the `Portal` component.

## New behavior

I have added JSDoc for the `Portal` component.

## Is this a breaking change (Yes/No):

No

## Additional Information

2024-04-18 22:48 UTC, hirotomoyamada commented
Please run `pnpm changeset` and select a `patch`.

2024-04-18 22:49 UTC, hirotomoyamada commented
@KekmaTime 

Hi, thanks for the PR.

Pls run `pnpm changeset` and select a `patch`.

2024-04-19 01:45 UTC, setodeve requested changes

2024-04-19 01:45 UTC, setodeve commented on package.json
Please remove this file from PR.

2024-04-19 01:45 UTC, setodeve commented on pnpm-lock.yaml
Please remove this file from PR.

2024-04-19 03:39 UTC, hirotomoyamada commented
@KekmaTime 

Rather than deleting the file, it removes it from the commit.

2024-04-19 15:24 UTC, setodeve commented on package.json
@KekmaTime 
Sorry about that.
Please do not include changes to `package.json` in this PR.

2024-04-19 15:25 UTC, setodeve commented on pnpm-lock.yaml
@KekmaTime 
Please do not include changes to `pnpm-lock.yaml` in this PR.

2024-04-20 15:12 UTC, closed without merging