feat(AudioPlayer): Add AudioPlayer component (#993)
yamada-ui/yamada-ui pull request #1671
Opened 2024-05-27 10:11 UTC by AVAM16

Closes #993 

## Description

> Add a brief description

Creation of the AudioPlayer component. It can take custom icons, titles, can show the duration and the current time stamp, can be used with a slider to move the timeline, can change background color and border color and can be muted with a mute button.

## Current behavior (updates)

> Please describe the current behavior that you are modifying

## New behavior

> Please describe the behavior or changes this PR adds

## Is this a breaking change (Yes/No):

## Additional Information

2024-05-27 15:19 UTC, 108yen requested changes
Will you add other features such as `onPlay` as linked in issue #993?

Finally, yamada check is also made.

2024-05-27 15:19 UTC, 108yen commented on packages/components/audio-player/src/audio-player.tsx
> +  useEffect(() => {
`useSageLayoutEffect`.

2024-05-27 15:19 UTC, 108yen commented on packages/components/audio-player/package.json
> +    "@yamada-ui/utils": "workspace:*"
Do not use yamada-ui components such as `Button` or `Slider`.
(`@yamada-ui/core` and `@yamada-ui/utils` are fine.)

2024-05-27 15:19 UTC, 108yen commented on packages/components/audio-player/tests/audio-player.test.tsx
> +    await a11y(container)
The `a11y` test should only be done once.

2024-05-29 10:43 UTC, AVAM16 commented
Given that I cannot use Yamada-UI components such as Button and Slider, I do not think it is worth to continue this PR. The entire feature revolved around using components from the same project. Thank you.

2024-05-29 10:43 UTC, closed without merging