Made the `Pagination`  component headless
yamada-ui/yamada-ui pull request #1965
Opened 2024-06-05 15:00 UTC by Haru-0001

Closes #1888

## Description

Made the Pagination component headless

## Current behavior (updates)

## New behavior

## Is this a breaking change (Yes/No):

No

## Additional Information

2024-06-05 15:21 UTC, koralle approved these changes

2024-06-05 18:10 UTC, fffk10 requested changes

2024-06-05 18:10 UTC, fffk10 commented on packages/components/pagination/src/pagination.tsx
I feel like this is also necessary, but is it unnecessary?

https://github.com/yamada-ui/yamada-ui/blob/8047466fc462c845dca7df2fefb5dd04414e584a/packages/components/pagination/src/pagination.tsx#L193-L199

2024-06-08 13:09 UTC, Haru-0001 commented on packages/components/pagination/src/pagination.tsx
I had lost track of it. I will correct it.

2024-06-08 18:30 UTC, Haru-0001 commented on packages/components/pagination/src/pagination.tsx
@fffk10 @koralle 
I have made the change. Could you please review it?

2024-06-09 07:05 UTC, nakayan5 approved these changes

2024-06-09 15:50 UTC, fffk10 commented on packages/components/pagination/src/pagination.tsx
LGTM!

2024-06-09 15:50 UTC, fffk10 approved these changes

2024-06-09 17:45 UTC, merged