Make Carousel component headless.
yamada-ui/yamada-ui pull request #2018
Opened 2024-06-08 07:12 UTC by balckowl

## Description

Make Carousel component headless.

## Is this a breaking change (Yes/No):

No.

## Additional Information

I left the CSSUIObject on line 315 of packages/components/carousel/src/carousel.tsx as is because I could not find the migration destination in packages/theme/src/components/carousel.ts.

2024-06-08 08:24 UTC, 108yen requested changes

2024-06-08 08:24 UTC, 108yen commented on packages/components/carousel/src/carousel-indicators.tsx
Line 75 is affected.
Is this not a problem?

2024-06-08 08:24 UTC, 108yen commented on packages/components/carousel/src/carousel-slide.tsx
Unnecessary change.

2024-06-08 08:24 UTC, 108yen commented on packages/components/carousel/src/carousel.tsx
You missed one place.

2024-06-08 08:24 UTC, 108yen commented on packages/theme/src/components/carousel.ts
> +    },
Unnecessary change.

2024-06-08 08:40 UTC, balckowl commented on packages/theme/src/components/carousel.ts
> +    },
Will it be okay if I revert this part?

2024-06-08 08:41 UTC, 108yen commented on packages/theme/src/components/carousel.ts
> +    },
Yes.

2024-06-08 12:06 UTC, balckowl commented on packages/theme/src/components/carousel.ts
> +    },
I have fixed it. Please confirm.

2024-06-11 16:36 UTC, fffk10 reviewed
I've confirmed.
I don't think there are any problems other than the points that have already been pointed out.

2024-06-13 23:23 UTC, hirotomoyamada commented
@108yen 

Please re-reviews.

2024-06-13 23:24 UTC, hirotomoyamada commented
@108yen @fffk10 

Please approval.

2024-06-14 03:09 UTC, 108yen commented on packages/components/carousel/src/carousel.tsx
@balckowl
You missed the location of `styles.container`.

2024-06-14 06:52 UTC, fffk10 submitted a review, later dismissed

2024-06-15 11:53 UTC, 108yen approved these changes

2024-06-15 22:57 UTC, hirotomoyamada approved these changes

2024-06-15 23:20 UTC, merged

2024-06-15 23:20 UTC, hirotomoyamada commented
Thanks!