fix: modified test
yamada-ui/yamada-ui pull request #2049
Opened 2024-06-10 14:10 UTC by illionillion

Closes None 

## Description

## Current behavior (updates)

## New behavior

## Is this a breaking change (Yes/No):

## Additional Information

2024-06-11 16:26 UTC, fffk10 submitted a review, later dismissed

2024-06-12 14:21 UTC, koralle approved these changes

2024-06-14 13:02 UTC, fffk10 requested changes
I commented, please check

2024-06-14 13:14 UTC, illionillion commented on packages/components/indicator/tests/indicator.test.tsx
@fffk10 OK i fixed it.
Thanks.

2024-06-14 13:19 UTC, fffk10 approved these changes

2024-06-14 17:58 UTC, merged