Enhance `Calendar` accessibilities
yamada-ui/yamada-ui pull request #2054
Opened 2024-06-10 16:20 UTC by koralle

Closes #2029

## Description

* add `grid` roles
* add `aria-label` to the elements with `grid` role

2024-06-11 12:46 UTC, Tomoya-Matsubara approved these changes

2024-06-11 14:12 UTC, nakayan5 approved these changes

2024-06-18 15:19 UTC, nakayan5 commented
@hirotomoyamada 
Which points are not enough?

2024-06-19 09:35 UTC, cidkumagai requested changes

2024-06-22 10:29 UTC, nakayan5 approved these changes

2024-06-22 11:31 UTC, cidkumagai approved these changes

2024-06-22 18:40 UTC, merged