fix _expanded to work
yamada-ui/yamada-ui pull request #2089
Opened 2024-06-12 16:30 UTC by cidkumagai

Closes #2057  

## Description
fix _expanded to work

2024-06-13 00:30 UTC, 108yen approved these changes

2024-06-13 06:12 UTC, hirotomoyamada commented
@cidkumagai @108yen 

Hi, thanks for the PR.

You removed `aria-expanded` and now you want to reinstate it?

Shouldn't we use `data-expanded`?

2024-06-13 13:11 UTC, cidkumagai commented
@hirotomoyamada 
Yes, I agree. We should use data-expanded. I will make the necessary changes.

Thank you.

2024-06-13 23:09 UTC, hirotomoyamada commented on packages/components/accordion/src/accordion-item.tsx
> +        "data-expanded": ariaAttr(isOpen),
Change `ariaAttr` to `dataAttr`.

2024-06-14 11:37 UTC, cidkumagai commented
@hirotomoyamada 
I have addressed the comments you provided and made the necessary corrections. Could you please review it again?

2024-06-14 13:33 UTC, setodeve submitted a review, later dismissed

2024-06-14 13:49 UTC, Haru-0001 approved these changes

2024-06-14 14:09 UTC, 108yen requested changes

2024-06-14 14:09 UTC, 108yen commented on packages/components/accordion/tests/accordion.test.tsx
> +    expect(button).toHaveAttribute("data-expanded", "")
No `""` is needed in other places.
```tsx
expect(button).toHaveAttribute("data-expanded")
```

2024-06-14 14:29 UTC, hirotomoyamada approved these changes

2024-06-14 14:29 UTC, 108yen approved these changes

2024-06-14 15:31 UTC, merged