Enhance `<Select>` component accessibilities
yamada-ui/yamada-ui pull request #2102
Opened 2024-06-14 15:47 UTC by koralle

Closes #1719

2024-06-15 03:40 UTC, 108yen requested changes
I think it should be in `getxxxProps` in `use-select.ts`, not in the `xxx.tsx` file.

2024-06-15 03:40 UTC, 108yen commented on packages/components/select/src/option-group.tsx
> +        aria-label={rest["aria-label"] ?? label}
I think you should adapt your writing style to that of `Slider`.
https://github.com/yamada-ui/yamada-ui/pull/2060

```tsx
{ className, color, h, height, minH, minHeight, children, "aria-label":ariaLabel, ...rest },

...

role="group"
aria-label=ariaLabel ?? label
```

2024-06-24 14:29 UTC, hirotomoyamada commented
@koralle 

Resolve conflicts.

2024-06-27 14:40 UTC, 108yen requested changes

2024-06-27 14:40 UTC, 108yen commented on packages/components/select/src/select.tsx
> +                      "aria-labelledby": props["aria-labelledby"],
Are there any duplicates?

2024-06-27 14:40 UTC, 108yen commented on packages/components/select/src/select.tsx
> +                      "aria-controls": listBoxId,
Is it possible to put `aria-controls` in the hook?

2024-06-27 14:40 UTC, 108yen commented on packages/components/select/src/option-group.tsx
> +              "aria-label": rest["aria-label"],
Can this be placed within the hook?

2024-07-03 06:13 UTC, 108yen commented on packages/components/select/src/use-select.ts
> +      role: "group",
It would be better to move it up to allow users to overwrite it.

2024-07-03 06:13 UTC, 108yen commented on packages/components/select/src/use-select.ts
> +        role: "option",
It would be better to move it up to allow users to overwrite it.

2024-07-03 13:21 UTC, koralle commented
@108yen 

There are many corrections needed, so I will recreate it below your comment. Thank you.

2024-07-03 13:21 UTC, closed without merging