Updated dependencies
yamada-ui/yamada-ui pull request #2126
Opened 2024-06-18 13:22 UTC by hirotomoyamada

## Description

Updated dependencies.

## Is this a breaking change (Yes/No):

No

2024-06-18 18:47 UTC, hirotomoyamada commented
@108yen @kurakke @taroj1205 @hirayamahiroto 

Fixed tests.

2024-06-19 04:20 UTC, 108yen requested changes
Do not include multiple assertions inside `waitFor`. Please put only the first one inside `waitFor`.
If you want to make `getxxx` asynchronous, use `findxxx`.


Are you sure that `forwardRef` is imported from `react` and not `@yamada-ui/core`?

2024-06-19 04:20 UTC, 108yen commented on packages/components/modal/src/dialog.tsx
Is `changeset` of `Modal` unnecessary?

2024-06-19 06:52 UTC, hirotomoyamada commented on packages/components/modal/src/dialog.tsx
This does not change the internal logic, it just resolves the TypeScript error. So there is no need for `changeset`.

2024-06-19 06:53 UTC, hirotomoyamada commented
@108yen 

This time, the `forwardRef` will be imported from React. The reason is that we want to genericize the component type.

2024-06-19 07:56 UTC, hirotomoyamada commented
@108yen 

Fixed tests.

2024-06-19 08:12 UTC, 108yen submitted a review, later dismissed

2024-06-19 15:31 UTC, kurakke submitted a review, later dismissed

2024-06-19 20:38 UTC, taroj1205 submitted a review, later dismissed

2024-06-20 10:13 UTC, kurakke approved these changes

2024-06-20 10:46 UTC, 108yen approved these changes

2024-06-20 11:20 UTC, merged