Increased test coverage for use-resize-observer
yamada-ui/yamada-ui pull request #2139
Opened 2024-06-20 10:42 UTC by kurakke

Closes #2079

## Description
Increased test coverage

## Current behavior (updates)

## New behavior

## Is this a breaking change (Yes/No):
No

## Additional Information

2024-06-20 11:44 UTC, 108yen requested changes

2024-06-20 11:44 UTC, 108yen commented on packages/hooks/use-resize-observer/tests/index.test.tsx
> -    await waitFor(() => expect(button.textContent).toBe("400 x 320"))
Dont remove `waitFor`.

2024-06-20 11:44 UTC, 108yen commented on .changeset/empty-rules-laugh.md
Please remove this file.

2024-06-20 11:44 UTC, 108yen commented on packages/hooks/use-resize-observer/tests/index.test.tsx
> +    const button = await screen.findByText("150 x 200")
```tsx
const button = await screen.findByRole("button")
```

2024-06-20 11:44 UTC, 108yen commented on packages/hooks/use-resize-observer/tests/index.test.tsx
> -
Dont remove.

2024-06-20 11:44 UTC, 108yen commented on packages/hooks/use-resize-observer/tests/index.test.tsx
> -
Dont remove.

2024-06-20 11:44 UTC, 108yen commented on packages/hooks/use-resize-observer/tests/index.test.tsx
> +
Similarly, use `afterAll` for post-processing.

2024-06-20 14:03 UTC, kurakke commented on .changeset/empty-rules-laugh.md
I fixed.
[1d0764b](https://github.com/yamada-ui/yamada-ui/pull/2139/commits/1d0764b2ce9e0add921759cfd1ac4555d671a7cc)

2024-06-20 14:14 UTC, kurakke commented
@108yen 
I have made the corrections as per your comments. Please check.

2024-06-20 14:14 UTC, 108yen approved these changes

2024-06-20 14:23 UTC, hoshico commented
@kurakke 
thanks for your PR!

The test at line 95 tends to fail after multiple attempts.
Please try running pnpm test use-resize-observer continuously for several dozen times.

If it tends to fail, I recommend using waitFor as referenced in line 48.

2024-06-21 01:29 UTC, 108yen commented
@kurakke 
Also, could you please move lines 48 and 95 to `toHaveTextContents`?

2024-06-24 12:57 UTC, hirotomoyamada approved these changes

2024-06-24 13:44 UTC, merged