Lucide icon imports and usage in components
yamada-ui/yamada-ui pull request #2174
Opened 2024-06-25 22:46 UTC by hirotomoyamada

Closes #2042

## Description

Lucide icon imports and usage in components.

## Is this a breaking change (Yes/No):

No

2024-06-26 16:03 UTC, 108yen requested changes

2024-06-27 11:09 UTC, hirotomoyamada commented on docs/contents/components/forms/autocomplete/index.ja.mdx
Fixed.

2024-06-27 11:09 UTC, hirotomoyamada commented on docs/contents/components/forms/multi-autocomplete/index.ja.mdx
Fixed.

2024-06-27 11:09 UTC, hirotomoyamada commented on docs/contents/components/forms/multi-select/index.ja.mdx
Fixed.

2024-06-27 11:09 UTC, hirotomoyamada commented on docs/contents/components/forms/native-select/index.ja.mdx
Fixed.

2024-06-27 11:10 UTC, hirotomoyamada commented on docs/contents/components/forms/select/index.ja.mdx
Fixed.

2024-06-27 14:51 UTC, 108yen approved these changes

2024-06-27 15:00 UTC, merged