Enhance the accessibility of MonthPicker `@yamada-ui/calendar` component
yamada-ui/yamada-ui pull request #2204
Opened 2024-06-30 11:46 UTC by cidkumagai

Closes #1733  

## Description

Enhance the accessibility of MonthPicker `@yamada-ui/calendar` component

2024-06-30 13:32 UTC, 108yen reviewed
It affects more than just `MonthPicker`, is that a problem?

2024-06-30 15:58 UTC, cidkumagai commented
@108yen 
Thank you comment.🙇‍♂️
I've checked the scope of the impact, and it's something that other issues will address, so I don't think it's a problem.
Corrections have been made where they should have been made.

2024-06-30 23:58 UTC, 108yen requested changes

2024-06-30 23:58 UTC, 108yen commented on packages/components/calendar/src/use-calendar-picker.ts
> +        "aria-controls": calendarId,
It is better to list it above `props`.

2024-07-01 12:36 UTC, 108yen approved these changes

2024-07-02 16:14 UTC, koralle commented on packages/components/calendar/src/use-calendar-picker.ts
> +  const calendarId = useId()
@cidkumagai 

It's okay to call useId() internally to generate an ID only when id is undefined.

```ts
 id ??= useId()
```

2024-07-02 16:18 UTC, koralle commented on packages/components/calendar/src/use-calendar-picker.ts
> +  const calendarId = useId()
or 

```ts
const calendarId = id ?? useId()
```

2024-07-04 15:04 UTC, koralle approved these changes

2024-07-05 12:16 UTC, hirotomoyamada approved these changes

2024-07-05 13:10 UTC, merged