[Select] Enhance `Select` component accessibility
yamada-ui/yamada-ui pull request #2238
Opened 2024-07-03 15:36 UTC by koralle

Closes #1719

2024-07-05 09:00 UTC, 108yen requested changes

2024-07-05 09:00 UTC, 108yen commented on packages/components/select/src/use-select.ts
>        ...props,
If the `props` has `id`, it is overwritten by the `...props` part.
I think this is fine.
```diff ts
+const id = useId()
 
const getListProps: MotionUIPropGetter<"ul"> = useCallback(
    (props = {}, ref = null) => ({
-      id: props.id ?? useId(),
+      id,
      as: "ul",
      ref: mergeRefs(listRef, ref),
      role: "listbox",
      tabIndex: -1,
      ...props,

```

2024-07-09 14:56 UTC, 108yen approved these changes

2024-07-11 02:47 UTC, hirotomoyamada approved these changes

2024-07-11 20:58 UTC, merged