Updated pnpm action to v4 in CI config
yamada-ui/yamada-ui pull request #2361
Opened 2024-07-26 11:36 UTC by hirotomoyamada

## Description

Updated pnpm action to v4 in CI config.

## Is this a breaking change (Yes/No):

No

2024-07-26 15:27 UTC, koralle requested changes

2024-07-26 15:27 UTC, koralle commented on .github/composite-actions/install/action.yml
>          version: 8
@hirotomoyamada 

> Remove the `version` listed here. It conflicts with the `packageManeger` version.

https://github.com/yamada-ui/yamada-theme/pull/13#pullrequestreview-2202093914

2024-07-29 10:53 UTC, hirotomoyamada commented on .github/composite-actions/install/action.yml
>          version: 8
Fixed.

2024-07-30 13:30 UTC, koralle approved these changes

2024-07-30 13:36 UTC, merged