Fix/context menu follows scrolling
yamada-ui/yamada-ui pull request #2499
Opened 2024-08-11 14:14 UTC by syunsuke-I

# [ContextMenu follows scrolling #2464](https://github.com/yamada-ui/yamada-ui/issues/2464)

## Description
Add scroll behavior test for ContextMenu and fix position during scroll

## Current behavior (updates)
Currently, the ContextMenu may not maintain its position relative to the viewport when the page is scrolled. This can lead to a poor user experience where the menu becomes misaligned or moves out of view.

## New behavior
- The ContextMenu now maintains its position relative to the viewport during page scroll.
- A new test has been added to verify this behavior, ensuring the menu's position remains constant when the container is scrolled.

## Is this a breaking change (Yes/No):
No

## Additional Information
This change improves the usability of the ContextMenu component, especially in long scrollable pages or complex layouts. The new test case provides additional confidence in the component's behavior and helps prevent future regressions.

The implementation involves:
1. Modifying the ContextMenu component to use `position: fixed` styling.
2. Adding a new test case in the existing test suite to simulate scrolling and verify menu position.
3. Updating relevant documentation to reflect the new scroll behavior.

Users of the ContextMenu component should see improved functionality without any need for changes on their part.

2024-08-15 04:02 UTC, hirotomoyamada commented
@syunsuke-I 

Hi, thanks for the PR!

This PR does not solve the problem.

What we want to achieve is that the `ContextMenu` does not follow the scroll and does not move from where it was first displayed.

I think the reason it follows the scroll is because of the `ContextMenuTrigger` `position: fixed` as mentioned in the issue.

```tsx
import type { CSSUIObject, HTMLUIProps } from "@yamada-ui/core"
import { ui, forwardRef } from "@yamada-ui/core"
import { PopoverAnchor, PopoverTrigger } from "@yamada-ui/popover"
import { cx, handlerAll } from "@yamada-ui/utils"
import type { MouseEvent } from "react"
import { useState } from "react"
import { useContextMenu } from "./context-menu"

type Position = { top: number; left: number }

export type ContextMenuTriggerProps = HTMLUIProps<"div">

export const ContextMenuTrigger = forwardRef<ContextMenuTriggerProps, "div">(
  ({ children, className, ...rest }, ref) => {
    const { styles } = useContextMenu()
    const [position, setPosition] = useState<Position>({ top: 0, left: 0 })

    const css: CSSUIObject = { ...styles.container }

    const onContextMenu = (ev: MouseEvent) => {
      setPosition({ top: ev.clientY, left: ev.clientX })
    }

    return (
      <>
        <PopoverAnchor>
          <ui.div
            className="ui-context-menu__anchor"
            style={{ position: "fixed", ...position }}
          />
        </PopoverAnchor>

        <PopoverTrigger>
          <ui.div
            ref={ref}
            className={cx("ui-context-menu", className)}
            __css={css}
            {...rest}
            onContextMenu={handlerAll(rest.onContextMenu, onContextMenu)}
          >
            {children}
          </ui.div>
        </PopoverTrigger>
      </>
    )
  },
)
```

2024-08-15 04:03 UTC, hirotomoyamada reviewed
@syunsuke-I 

Hi, thanks for the PR!

This PR does not solve the problem.

What we want to achieve is that the `ContextMenu` does not follow the scroll and does not move from where it was first displayed.

I think the reason it follows the scroll is because of the `ContextMenuTrigger` `position: fixed` as mentioned in the issue.

```tsx
import type { CSSUIObject, HTMLUIProps } from "@yamada-ui/core"
import { ui, forwardRef } from "@yamada-ui/core"
import { PopoverAnchor, PopoverTrigger } from "@yamada-ui/popover"
import { cx, handlerAll } from "@yamada-ui/utils"
import type { MouseEvent } from "react"
import { useState } from "react"
import { useContextMenu } from "./context-menu"

type Position = { top: number; left: number }

export type ContextMenuTriggerProps = HTMLUIProps<"div">

export const ContextMenuTrigger = forwardRef<ContextMenuTriggerProps, "div">(
  ({ children, className, ...rest }, ref) => {
    const { styles } = useContextMenu()
    const [position, setPosition] = useState<Position>({ top: 0, left: 0 })

    const css: CSSUIObject = { ...styles.container }

    const onContextMenu = (ev: MouseEvent) => {
      setPosition({ top: ev.clientY, left: ev.clientX })
    }

    return (
      <>
        <PopoverAnchor>
          <ui.div
            className="ui-context-menu__anchor"
            style={{ position: "fixed", ...position }}
          />
        </PopoverAnchor>

        <PopoverTrigger>
          <ui.div
            ref={ref}
            className={cx("ui-context-menu", className)}
            __css={css}
            {...rest}
            onContextMenu={handlerAll(rest.onContextMenu, onContextMenu)}
          >
            {children}
          </ui.div>
        </PopoverTrigger>
      </>
    )
  },
)
```

2024-08-15 05:26 UTC, syunsuke-I commented
I apologize. I only confirmed the behavior with test code and haven't actually verified the real behavior. Could you please tell me how to check the behavior locally(myself)?

2024-08-15 13:01 UTC, haru-036 submitted a review, later dismissed
https://github.com/yamada-ui/yamada-ui/blob/main/CONTRIBUTING.md
Please refer to this
You can check it out in the storybook

2024-08-15 14:06 UTC, syunsuke-I commented
I can confirm the contextMenu using Storybook, but I can't verify if it follows the scroll. This is because I can't scroll on Storybook.

2024-08-15 15:29 UTC, haru-036 commented
@syunsuke-I 
You can edit it.

2024-08-15 21:54 UTC, syunsuke-I commented
I'll try it. Thank you

2024-08-15 23:12 UTC, syunsuke-I commented
I have confirmed that the contextMenu works correctly and follows the scroll in Storybook. However, I'm unsure whether these Storybook changes should be committed. They're useful for verifying the scroll behavior, but that's their only purpose. Should we include these changes in our commit...?

https://github.com/user-attachments/assets/4c8769f4-836d-4b96-924e-b0693b0ca03e

2024-08-17 05:56 UTC, 108yen requested changes
Do not include storybook changes.

2024-08-17 05:56 UTC, 108yen commented on .changeset/hungry-otters-own.md
> +"@yamada-ui/theme": major
Please change.
```diff md
-"@yamada-ui/menu": major
+"@yamada-ui/menu": patch
-"@yamada-ui/theme": major
```

2024-08-17 05:56 UTC, 108yen commented on packages/components/menu/tests/menu.test.tsx
The added test will pass without change.
The test must fail if it has unintended behavior.
It seems difficult to test on this, so it can be removed.

2024-08-17 11:23 UTC, syunsuke-I commented
I have addressed the review comments.

2024-08-17 12:00 UTC, 108yen approved these changes

2024-08-17 13:10 UTC, syunsuke-I commented
Are there any tasks left for me?

2024-08-17 23:55 UTC, hirotomoyamada commented
@syunsuke-I 

Hi, thanks for the fix.

You have no remaining tasks:)

There are other PRs, so this PR will be merged after that.

2024-08-17 23:56 UTC, hirotomoyamada approved these changes

2024-08-18 00:24 UTC, hirotomoyamada commented
Thanks!

2024-08-18 00:24 UTC, merged