Add explanation for "Adding Children" in ColorPicker
yamada-ui/yamada-ui pull request #2566
Opened 2024-08-15 10:33 UTC by hironokobari

Closes #2406

## Description

Add explanation for "Adding Children" in `ColorPicker`

## Is this a breaking change (Yes/No)

No

2024-08-17 06:49 UTC, odendayoko requested changes
@hironokobari
Thank you for the implementation.
 I apologize for the minor feedback, but I have left some comments. Could you please make the necessary adjustments?

2024-08-17 06:49 UTC, odendayoko commented on docs/contents/components/forms/color-picker/index.ja.mdx
> +
@hironokobari
The content of the Japanese text and English text differs. 
The English version is more specific and clearer, so I recommend modifying the Japanese text to match the English version.

e.g.,「独自の要素を追加するには、ColorPickerコンポーネントに子要素を挿入してください。」

2024-08-17 06:49 UTC, odendayoko commented on docs/contents/components/forms/color-picker/index.mdx
> +### Adding Children
@hironokobari
Most headings use verbs in the imperative form (e.g., "Change Variant", "Set Default Value"). 
To maintain consistency with other headings in the document, could you change the heading to `Add Children`?

2024-08-17 06:57 UTC, odendayoko requested changes
@hironokobari
Thank you for the implementation.
I apologize for the minor feedback, but I have left some comments. Could you please make the necessary adjustments?

2024-08-17 06:57 UTC, odendayoko commented on docs/contents/components/forms/color-picker/index.mdx
> +### Adding Children
@hironokobari
Most headings use verbs in the imperative form (e.g., "Change Variant", "Set Default Value").
To maintain consistency with other headings in the document, could you change the heading to Add Children?

2024-08-17 06:57 UTC, odendayoko commented on docs/contents/components/forms/color-picker/index.ja.mdx
> +`ColorPicker`コンポーネントに子要素を追加できます。
@hironokobari
The content of the Japanese text and English text differs.
The English version is more specific and clearer, so I recommend modifying the Japanese text to match the English version.

e.g.,「独自の要素を追加するには、ColorPickerコンポーネントに子要素を挿入してください。」

2024-08-17 12:13 UTC, odendayoko approved these changes
@hironokobari
Thank you! LGTM

2024-08-19 14:23 UTC, hirotomoyamada commented on docs/contents/components/forms/color-picker/index.ja.mdx
> +### 子要素の追加
Change `子要素の追加` to `ドロップダウンに要素を追加する`.

2024-08-19 14:26 UTC, hirotomoyamada commented on docs/contents/components/forms/color-picker/index.ja.mdx
> +独自の要素を追加するには、`ColorPicker`コンポーネントに子要素を挿入してください。
Change to

```
独自の要素を追加するには、`ColorPicker`コンポーネントに子要素を挿入してください。
```

```
ドロップダウンに要素を追加する場合は、`children`に要素を設定します。
`children`には、`value`と`onClose`が提供されます。これを利用して、内部状態にアクセスすることができます。
```

2024-08-19 14:28 UTC, hirotomoyamada commented on docs/contents/components/forms/color-picker/index.mdx
> +To add custom content, insert children elements into the `ColorPicker` component.
Change

```
To add custom content, insert children elements into the `ColorPicker` component.
```

to

```
To add elements to a dropdown, set the elements to the `children` property.
The `children` are provided with `value` and `onClose` methods, which can be used to access the internal state.
```

2024-08-19 14:30 UTC, hirotomoyamada commented on docs/contents/components/forms/color-picker/index.mdx
> +### Add Children
Change `Add Children` to `Adding elements to a dropdown`.

2024-08-20 12:06 UTC, hironokobari commented
@hirotomoyamada @odendayoko 
Thanks for pointing it out! Fixed.

2024-08-20 12:33 UTC, hirotomoyamada approved these changes

2024-08-20 12:48 UTC, merged