test: add onKeyDown and onKeyUp tests
yamada-ui/yamada-ui pull request #2598
Opened 2024-08-19 13:15 UTC by chida09

https://github.com/yamada-ui/yamada-ui/issues/2357

## Description

add onKeyDown and onKeyUp tests for the Radio component

## Current behavior (updates)

## New behavior

## Is this a breaking change (Yes/No):

No

## Additional Information

2024-08-22 09:44 UTC, 108yen requested changes
There is no need to test for `onKeyDown` or `onKeyUp` passed as `props`.
Notice that `setActive` is executed in response to the `keyDown` or `keyUp` event.
Please test if the change is reflected in `isActive` according to the event.

2024-08-22 14:36 UTC, chida09 commented
@108yen 
I've modified the tests based on your feedback. Could you please review the changes?

2024-08-22 20:45 UTC, 108yen approved these changes

2024-08-23 04:43 UTC, hirotomoyamada approved these changes

2024-08-23 04:43 UTC, merged

2024-08-23 04:43 UTC, hirotomoyamada commented
Thanks!