docs: typo in description of `Toggle`
yamada-ui/yamada-ui pull request #2650
Opened 2024-08-24 12:07 UTC by UHAsikakutou

## Description

I have corrected a typo in the description in `Toggle`.
`Toggle`コンポーネントの説明文にあった誤字を修正しました。

## Is this a breaking change (Yes/No):

No

2024-08-24 12:26 UTC, hirotomoyamada commented on .changeset/dirty-dragons-tease.md
Hi, this file is not needed. Please delete it.

2024-08-24 20:56 UTC, UHAsikakutou commented on .changeset/dirty-dragons-tease.md
Thank you for your review.
I have delete it.

2024-08-25 05:05 UTC, odendayoko requested changes
@UHAsikakutou 
Hi, thanks for the PR.
I apologize for the inconvenience, but could you please make two additional changes?

2024-08-25 05:19 UTC, UHAsikakutou commented
Hello, @odendayoko . 
Thank you for your review.
I have corrected the points you mentioned.

2024-08-25 14:30 UTC, odendayoko approved these changes
@UHAsikakutou 
LGTM Thank you!!

2024-08-25 15:44 UTC, hirotomoyamada commented
Thanks!

2024-08-25 15:45 UTC, hirotomoyamada approved these changes

2024-08-25 15:45 UTC, merged