test: add tests for modal placement
yamada-ui/yamada-ui pull request #2651
Opened 2024-08-24 13:35 UTC by chida09

Closes https://github.com/yamada-ui/yamada-ui/issues/2356

## Description

add tests for modal placement for the Modal component

## Current behavior (updates)

## New behavior

## Is this a breaking change (Yes/No):

No

## Additional Information

2024-08-24 13:48 UTC, chida09 commented on packages/components/modal/tests/modal.test.tsx
> +import { a11y, act, fireEvent, render, screen, waitFor } from "@yamada-ui/test"
Rearranged the order of imported items alphabetically.

2024-08-26 05:44 UTC, 108yen requested changes
Only one assertion can be included within `waitFor`.

2024-08-26 06:26 UTC, chida09 commented
You're right. I'll make the correction.

2024-08-26 13:49 UTC, 108yen approved these changes

2024-08-26 16:06 UTC, hirotomoyamada approved these changes

2024-08-26 16:06 UTC, merged