Add a new `minSelectValues` prop to `RangeDatePicker`
yamada-ui/yamada-ui pull request #2689
Opened 2024-08-31 06:54 UTC by Shunii85

Closes #2467 

## Description
Add a new `minSelectValues` prop to `RangeDatePicker`.

2024-08-31 14:31 UTC, 108yen requested changes

2024-08-31 14:31 UTC, 108yen commented on stories/components/forms/range-date-picker.stories.tsx
> +
Unnecessary as it is a duplicate.

2024-09-10 06:32 UTC, hirotomoyamada commented
@Shunii85 @108yen 

Hi, have you finished revising your review?If so, please submit the review again.

2024-09-10 06:36 UTC, 108yen submitted a review, later dismissed

2024-09-17 04:15 UTC, hirotomoyamada commented
@Shunii85 

Hi, conflicts appear to be occurring. Please fix.

2024-09-17 18:30 UTC, hirotomoyamada approved these changes

2024-09-17 18:32 UTC, merged