Fix/icon button/a11y
yamada-ui/yamada-ui pull request #2734
Opened 2024-09-07 10:31 UTC by kurakke

Closes #2214

## Description
Make aria-label of IconButton mandatory and

## Is this a breaking change (Yes/No):
Yes

## Additional Information
No

2024-09-14 15:22 UTC, kurakke commented on docs/pages/examples/mail/detail.tsx
> +              aria-label="Reply all mail"
fixed
[f22f733](https://github.com/yamada-ui/yamada-ui/pull/2734/commits/f22f7335a3e6b373c9207a1dc57b4623922e5373)

2024-09-14 15:22 UTC, kurakke commented on examples/vite/src/components/layouts/header.tsx
fixed
[f22f733](https://github.com/yamada-ui/yamada-ui/pull/2734/commits/f22f7335a3e6b373c9207a1dc57b4623922e5373)

2024-09-15 02:21 UTC, odendayoko requested changes

2024-09-15 02:21 UTC, odendayoko commented on packages/core/src/generated-theme.types.ts
@kurakke 
Thank you for the changes! 
Do you need to fix this file in this PR? It might be better to address this in another PR.

2024-09-15 03:30 UTC, kurakke commented on packages/core/src/generated-theme.types.ts
I accidentally put the wrong change in the commit.
I fixed it.
[a9627bd](https://github.com/yamada-ui/yamada-ui/pull/2734/commits/a9627bd43e218c895c20a9e1507929439a351e89)

2024-09-15 15:10 UTC, odendayoko approved these changes
@kurakke 
Thanks!! LGTM🧡

2024-09-15 16:10 UTC, kurakke commented
Since no changeset was added, I added a changeset.
Please review.
@odendayoko

2024-09-16 08:10 UTC, odendayoko submitted a review, later dismissed

2024-09-23 07:13 UTC, hirotomoyamada approved these changes

2024-09-23 08:20 UTC, merged