fix : add displayName and __ui__ to select component
yamada-ui/yamada-ui pull request #2955
Opened 2024-09-24 20:37 UTC by kiran0022

Closes #2901

## Description

Set displayName for the @yamada-ui/select component to make debugging easier.
This change improves the ability to identify the component name in development tools.

## Current behavior (updates)

Currently, displayName is not set for the @yamada-ui/select component, making it difficult to identify the component in debugging tools like React Developer Tools.

## New behavior

With displayName set, the @yamada-ui/select component now displays its name correctly in debugging tools like React Developer Tools, making it easier for developers to identify and debug the component.

## Is this a breaking change (Yes/No):

No

## Additional Information

None

2024-09-25 01:57 UTC, illionillion requested changes
@kiran0022 

Thank for PR!!

Please all components of files in the same directory  other than select.tsx should be modified in the same way.

2024-09-25 09:01 UTC, kiran0022 commented
@illionillion 

Thanks for the feedback! 
I've updated the related select components accordingly. Let me know if you need anything else.

2024-09-25 10:37 UTC, illionillion requested changes
@kiran0022 

Thanks for the correction.

Please apply the `displayName` and `__ui__` fixes to all components.

For normal `FC` components that do not use `forwardRef`, import the `FC` from `@yamada-ui/core` and modify it.

If you are told that there is no `FC` type in `@yamada-ui/core`, please sync the latest contents to the fork repository and merge it into your branch.

2024-09-25 10:37 UTC, illionillion commented on .changeset/four-readers-doubt.md
Multiple changesets are not needed for a single package change, and this is not a `major` change.
Please delete this.

2024-09-25 10:37 UTC, illionillion commented on packages/components/select/src/select.tsx
The `SelectField` should be modified in the same way.

2024-09-25 10:37 UTC, illionillion commented on packages/components/select/src/select-icon.tsx
The `SelectClearIcon` should be modified in the same way.

2024-09-25 10:37 UTC, illionillion commented on packages/components/select/src/select-icon.tsx
import `FC` from `@yamada-ui/core`

2024-09-25 10:37 UTC, illionillion commented on packages/components/select/src/option.tsx
Fix here too with all components.

2024-09-25 10:37 UTC, illionillion commented on packages/components/select/src/multi-select.tsx
Fix here too with all components.

2024-09-27 07:19 UTC, kiran0022 commented
@illionillion

Thanks for your guidance! 
I've addressed the change requests and updated the PR. Let me know if there's anything else you need!

2024-09-27 16:18 UTC, hirotomoyamada commented
Thanks!

2024-09-27 17:51 UTC, merged