feat: ally Control
yamada-ui/yamada-ui pull request #2961
Opened 2024-09-25 17:04 UTC by taku10101

Closes #2924 

## Description

add aria-controls and role

## Current behavior (updates)

## New behavior

## Is this a breaking change (Yes/No):
no

## Additional Information

2024-09-26 00:17 UTC, kaehehehe requested changes

2024-09-26 00:17 UTC, kaehehehe commented on .changeset/cool-cycles-build.md
> +"@yamada-ui/color-picker": minor
```suggestion
"@yamada-ui/color-picker": patch
```

2024-09-26 08:31 UTC, kaehehehe commented
Two tests have failed. Please check.　@taku10101 

<img width="1052" alt="스크린샷 2024-09-26 17 26 24" src="https://github.com/user-attachments/assets/6a3c81af-c42e-4b4b-b96d-7dfcebbcf170">
d. Please check.

2024-09-26 08:39 UTC, kaehehehe commented
The tests are failing right now, so could you pull the main branch and push it again? @taku10101

2024-09-27 01:26 UTC, kaehehehe approved these changes
LGTM!  💯 💯 💯

2024-09-28 16:14 UTC, kaehehehe requested changes

2024-09-29 03:45 UTC, taku10101 commented on packages/components/color-picker/src/color-picker.tsx
> +    }, [])
@kaehehehe 
If you turn it off, you will get this Incomplete
Is it safe to ignore this?

https://dequeuniversity.com/rules/axe/4.10/aria-allowed-role?application=axeAPI
<img width="962" alt="スクリーンショット 2024-09-29 12 43 45" src="https://github.com/user-attachments/assets/dabb893e-e283-4730-a776-f4060b01fecc">

2024-09-29 07:57 UTC, kaehehehe requested changes

2024-09-29 07:57 UTC, kaehehehe commented on packages/components/color-picker/src/color-picker.tsx
> +    }, [])
It's not needed, so just delete it.  @taku10101

2024-09-29 08:00 UTC, kaehehehe reviewed
一度、Approveしてしまったんですが、修正をお願いします。申し訳ないです！

2024-09-29 08:07 UTC, kaehehehe commented
Please revert all code related to 'id' and use 'useId' instead. Also, fix the code as follows.



```tsx
              <PopoverTrigger>
                <ColorPickerField
                  role="combobox" // ✅
                  aria-controls={id} // ✅
                  h={h}
                  minH={minH}
                  {...getFieldProps(inputProps, ref)}
                />
              </PopoverTrigger>

              {eyeDropperSupported && withEyeDropper ? (
                <ColorPickerEyeDropper
                  {...getEyeDropperProps(eyeDropperProps)}
                />
              ) : null}
            </ui.div>

            <Portal {...portalProps}>
              <PopoverContent
                containerProps={{ // ✅
                  id, 
                }}
                className="ui-color-picker__content"
                __css={{ ...styles.content }}
              >
                <ColorSelector
                  className="ui-color-picker__picker"
                  {...getSelectorProps({
                    saturationSliderRef,
                    saturationSliderProps,
                    swatchesProps,
                    hueSliderRef,
                    hueSliderProps,
                    alphaSliderRef,
                    alphaSliderProps,
                    channelsProps,
                    channelProps,
                  })}
                >
```

2024-09-29 13:44 UTC, kaehehehe requested changes

2024-09-29 13:44 UTC, kaehehehe commented on packages/components/color-picker/src/color-picker.tsx
> +                aria-labelledby="color-picker-label"
```suggestion
```

2024-09-29 13:44 UTC, kaehehehe commented on packages/components/color-picker/src/color-picker.tsx
> +                  aria-controls={id}
Please fix as below.
```suggestion
                  role="combobox"
                  aria-controls={id}
```

2024-09-30 12:55 UTC, kaehehehe requested changes

2024-09-30 12:55 UTC, kaehehehe commented on packages/components/color-picker/src/use-color-picker.ts
> +
Please remove unnecessary line breaks.

2024-09-30 12:55 UTC, kaehehehe commented on packages/components/color-picker/src/use-color-picker.ts
> +
Please remove unnecessary line breaks.

2024-10-01 12:54 UTC, kaehehehe submitted a review, later dismissed
Thanks!! :)

2024-10-06 01:17 UTC, hirotomoyamada commented
Please resolve conflicts.

2024-10-06 01:17 UTC, hirotomoyamada commented
@taku10101 

Please resolve conflicts.

2024-10-07 11:55 UTC, kaehehehe requested changes
Please check for build, ESLint, and TypeScript errors. @taku10101 
![스크린샷 2024-10-07 20 50 48](https://github.com/user-attachments/assets/4da2c1e7-67d6-46b4-b6f4-3f69236e69de)
![스크린샷 2024-10-07 20 50 32](https://github.com/user-attachments/assets/3da59227-5fbf-411b-846c-027dbdaf1a15)
![스크린샷 2024-10-07 20 50 17](https://github.com/user-attachments/assets/4ff50ed7-62c0-4df8-9ca6-facfc6e460d2)

2024-10-08 03:58 UTC, kaehehehe approved these changes
Thanks! 👍🏼 @taku10101

2024-10-15 06:53 UTC, hirotomoyamada commented
There are too many commits for the PR. 

This PR is closed. Please put together your commitments again and submit them.

2024-10-15 06:53 UTC, closed without merging