fix: set `displayname` and `__ui__`
yamada-ui/yamada-ui pull request #2978
Opened 2024-09-27 14:02 UTC by darkcat666

Closes #2895 

## Description

The component "@yamada-ui/rating" uses forwardRef, but displayName is not set, making it difficult to see the display in [React Developer Tools](https://github.com/facebook/react/tree/main/packages/react-devtools).

## New behavior

Set `displayNane` and `__ui__`

## Is this a breaking change (Yes/No):

No

2024-09-28 06:12 UTC, illionillion requested changes

2024-09-28 06:12 UTC, illionillion commented on packages/components/rating/src/rating-item.tsx
@darkcat666 

Thank for PR!!

Please import `FC` from `@yamada-ui/core`.
StarIcon and RatingIcon should be modified in the same way.

2024-09-29 09:29 UTC, darkcat666 commented on packages/components/rating/src/rating-item.tsx
@illionillion 

I added missing import `FC` from @yamada-ui/core.
Thank you for pointing that out.

2024-09-30 01:28 UTC, hinataOhyama approved these changes

2024-10-01 04:04 UTC, illionillion commented on .changeset/fuzzy-penguins-hammer.md
Only one changeset is required per package change.

2024-10-01 04:06 UTC, illionillion commented on packages/components/rating/src/rating-item.tsx
This has not been corrected.

> StarIcon and RatingIcon should be modified in the same way.

2024-10-01 12:20 UTC, darkcat666 commented on .changeset/fuzzy-penguins-hammer.md
I deleted duplicated changeset.

2024-10-01 12:21 UTC, darkcat666 commented on packages/components/rating/src/rating-item.tsx
I fixed StarIcon.
Thank you.

2024-10-02 12:20 UTC, darkcat666 commented on packages/components/rating/src/rating-item.tsx
Sorry, I overlooked What needs to be fixed.
I fixed it for sure this time.

2024-10-03 03:28 UTC, illionillion approved these changes
LGTM

2024-10-04 12:03 UTC, hirotomoyamada approved these changes

2024-10-05 17:33 UTC, hirotomoyamada commented
Thanks!

2024-10-05 17:34 UTC, merged