feat: set display name and UI for markdown
yamada-ui/yamada-ui pull request #2979
Opened 2024-09-27 14:26 UTC by 0xtkey256

Closes Closes #2978

## Description

set for the component of `@yamada-ui/markdown`

## Current behavior (updates)

## New behavior

## Is this a breaking change (Yes/No):

## Additional Information

2024-09-27 23:14 UTC, cidkumagai requested changes

2024-09-27 23:14 UTC, cidkumagai commented on packages/components/markdown/src/markdown.tsx
@0xtkey256 
I think the Code component also needs to be modified.

2024-09-27 23:55 UTC, 0xtkey256 commented on packages/components/markdown/src/markdown.tsx
@cidkumagai 
Thanks, I've set the `displayname` and `__ui__`, and also changed `FC` import from `@yamada-ui/core`. Please review the change.

2024-09-29 09:00 UTC, hirotomoyamada approved these changes

2024-09-29 09:11 UTC, merged