fix: displayName is not set for the component of "@yamada-ui/pagination" #2889
yamada-ui/yamada-ui pull request #3021
Opened 2024-09-29 16:01 UTC by Utkarshrajmishra

Closes https://github.com/yamada-ui/yamada-ui/issues/2889
### Description

Set displayName for the @yamada-ui/pagination component to make debugging easier.
This change improves the ability to identify the component name in development tools.

### Current behavior (updates)

Currently, displayName is not set for the @yamada-ui/pagination component, making it difficult to identify the component in debugging tools like React Developer Tools.
New behavior

With displayName set, the @yamada-ui/pagination component now displays its name correctly in debugging tools like React Developer Tools, making it easier for developers to identify and debug the component.

### Is this a breaking change (Yes/No):
No.
### Additional Information
None.

2024-10-01 00:28 UTC, illionillion requested changes
@Utkarshrajmishra 
Thank for PR!!

Please Modify `pagination-item.tsx` and `pagination-icon.tsx` in the same way.
Import `FC` from `@yamada-ui/core` for normal components that do not use `forwardRef`

2024-10-03 15:35 UTC, Utkarshrajmishra commented
Hey @illionillion, I have made the required changes. Please have a look.

2024-10-04 01:14 UTC, illionillion commented on packages/components/pagination/src/pagination-icon.tsx
@Utkarshrajmishra 
Please import `FC` from `@yamada-ui/core`

2024-10-04 01:14 UTC, illionillion commented on packages/components/pagination/src/pagination-item.tsx
Please import `FC` from `@yamada-ui/core`

2024-10-06 01:17 UTC, hirotomoyamada commented
Please resolve conflicts.

2024-10-06 01:18 UTC, hirotomoyamada commented
@Utkarshrajmishra 

Please resolve conflicts.

2024-10-07 09:09 UTC, hirotomoyamada commented
@Utkarshrajmishra

Hi, Thanks for the PR!

A week has passed since this PR was created, so maintainers will be joining this PR.

2024-10-08 02:48 UTC, illionillion approved these changes

2024-10-08 12:55 UTC, hirotomoyamada approved these changes

2024-10-08 13:07 UTC, merged