fix(number-input): add displayName and __ui__ properties to improve d…
yamada-ui/yamada-ui pull request #3022
Opened 2024-09-29 17:27 UTC by Itsuki54

### Description

Added `displayName` and `__ui__` properties to the `@yamada-ui/number-input` component to improve debugging in React Developer Tools and ensure proper internal usage within Yamada UI.

### Current behavior (updates)

Currently, the `@yamada-ui/number-input` component does not have `displayName` or `__ui__` set, making it difficult to identify in React Developer Tools.

### New behavior

With this change, the `@yamada-ui/number-input` component now has both `displayName` and `__ui__` set, making it easier to identify in React Developer Tools and improving internal management within Yamada UI.

### Is this a breaking change (Yes/No):

**No**

### Additional Information

There are no breaking changes, so this update should not affect existing Yamada UI users.

2024-09-30 00:45 UTC, illionillion requested changes
@Itsuki54 

Thank for PR!!

Please correct them.

2024-09-30 00:45 UTC, illionillion commented on .changeset/bright-toes-repeat.md
> +"@yamada-ui/number-input": minor
Please change to `patch`.

```suggestion
"@yamada-ui/number-input": patch
```

2024-09-30 00:45 UTC, illionillion commented on packages/components/number-input/src/number-input.tsx
- `NumberInputField`
- `NumberInputAddon`
- `NumberDecrementStepper`
- `NumberIncrementStepper`

Please fix it the same way for all components.

2024-09-30 00:45 UTC, illionillion commented on packages/components/number-input/src/number-input.tsx
All other components, if any, should be modified in the same way.

2024-09-30 12:26 UTC, cidkumagai commented
@Itsuki54

Hi, Thank for PR.
Since one changeset should be enough, please delete one of them.

2024-09-30 13:34 UTC, illionillion approved these changes
LGTM

2024-09-30 16:00 UTC, cidkumagai approved these changes

2024-10-01 17:36 UTC, hirotomoyamada approved these changes

2024-10-04 11:55 UTC, hirotomoyamada approved these changes

2024-10-04 15:45 UTC, merged