fix(tabs): added necessary aria attributes to Tab and TabPanel component
yamada-ui/yamada-ui pull request #3147
Opened 2024-10-16 08:43 UTC by taiseiiiii

Closes # 1636

## Description

Added necessary aria attributes to Tab and TabPanel component

## Current behavior (updates)

Regarding Tab component, it doesn't have `id` and `aria-controls`
As for TabPanel, it doesn't have `id` and `aria-labelledby`

## New behavior

The Tab and TabPanel are now associated with each other.

## Is this a breaking change (Yes/No):

No

2024-10-16 11:12 UTC, 108yen requested changes
Closes issue link is broken.

2024-10-16 11:12 UTC, 108yen commented on packages/components/tabs/src/tabs.tsx
Is it not possible to pass only `uuid` to props?
We can generate the respective ids at the destination we pass them to.
The name `uuid` is rarely used. So please rename `id`.

2024-10-16 11:48 UTC, taiseiiiii commented on packages/components/tabs/src/tabs.tsx
@108yen 

> Closes issue link is broken.

Sorry, I have overlooked. I just correct it.

> Is it not possible to pass only uuid to props?

It implies only uuid should be defined in TabsContext?

> The name uuid is rarely used. So please rename id.

I consider `baseId` more preferable according to your feedback
Is it proper?

2024-10-16 12:22 UTC, 108yen commented on packages/components/tabs/src/tabs.tsx
@taiseiiiii 
> It implies only uuid should be defined in TabsContext?

Yes. If it is possible.
> I consider baseId more preferable according to your feedback
> Is it proper?

That might still be a good idea.

2024-10-16 12:42 UTC, taiseiiiii commented on packages/components/tabs/src/tabs.tsx
@108yen 

> Yes. If it is possible.

Sorry, I still don't understand.
If you have any idea of this implementation, would it be possible to share a few example?
I think each props(tabIds, tabPanelIds) should be defined in TabsContext. 
It's because the Tab component and the TabPanel component need to reference each other's ids.

2024-10-16 15:04 UTC, 108yen commented on packages/components/tabs/src/tabs.tsx
@taiseiiiiiii 
Why don't we do the same on the tabpanel side?

2024-10-16 15:32 UTC, taiseiiiii commented on packages/components/tabs/src/tabs.tsx
@108yen 
Sorry, I may have been mistaken.
In the beginning, I think this component should set the id from user Input.
Because, in the document of Tabs, ARIA Roles and Attributes section includes following statement.

https://yamada-ui.com/components/disclosure/tabs/accessibility

> The id used to associate with role="tabpanel".

That's so I implemented current source code.

Does that mean that such a requirement is not necessary in the first place?
```
<Tabs>
      <Tab id="tab-1">孫悟空</Tab>
      <Tab>ベジータ</Tab>
      <Tab>フリーザ</Tab>

      <TabPanel id="tabpanel-1">
        <Text>クリリンのことか……クリリンのことかーーーっ！！！！！</Text>
      </TabPanel>

~~~~~~~~
</Tabs>
```

2024-10-16 15:48 UTC, 108yen commented on packages/components/tabs/src/tabs.tsx
@taiseiiiii 
If user passes id props, user must manage ids. We should only consider when user doesn't pass ids.
The way to manage IDs on the user side should be written in the documentation.

2024-10-16 16:11 UTC, taiseiiiii commented on packages/components/tabs/src/tabs.tsx
@108yen 
I finally understand!!!
I apologize for checking so many times.

I've just corrected according to your feedback.
Would it be possible to confirm again?

2024-10-17 00:55 UTC, 108yen commented
@taiseiiiii 
Isn't it a problem that the tab id and the tab panel id are the same?

2024-10-17 03:35 UTC, taiseiiiii commented
@108yen 
Does the following approach seem suitable?
Add the suffix to the each id

`tab.tsx`
```
    const tabId = `${baseId}-${index}-tab`
    const tabpanelId = `${baseId}-${index}-tabpanel`

   return (
      <ui.button
        id={tabId}
        className={cx("ui-tabs__tab", className)}
        role="tab"
        __css={css}
        {...props}
        {...rest}
        type="button"
        aria-controls={tabpanelId}
```

`tab-panel.tsx`
```
    const tabpanelId = `${baseId}-${index}-tabpanel`
    const tabId = `${baseId}-${index}-tab`

    return (
      <ui.div
        id={tabpanelId}
        ref={ref}
        className={cx("ui-tabs__panel", className)}
        role="tabpanel"
        __css={css}
        {...rest}
        aria-labelledby={tabId}
```

2024-10-17 03:59 UTC, 108yen commented
@taiseiiiii 
Yes

2024-10-17 04:09 UTC, taiseiiiii commented
@108yen 
I've just addressed your feedback.
Would it be possible to confirm modifications?

2024-10-17 12:24 UTC, 108yen requested changes

2024-10-17 12:24 UTC, 108yen commented on packages/components/tabs/src/tab-panel.tsx
> +        aria-labelledby={tabId}
User can't change `aria-labelledby`.

2024-10-17 12:24 UTC, 108yen commented on packages/components/tabs/src/tab.tsx
> +        aria-controls={tabpanelId}
User can't change `aria-controls`.

2024-10-18 12:54 UTC, taiseiiiii commented
@108yen 
Sorry. I've just corrected.
Please review again.

2024-10-18 12:55 UTC, 108yen submitted a review, later dismissed

2024-10-20 05:03 UTC, 108yen commented
@taiseiiiii 
We were wrong.
We need to adjust `aria-controls` and `aria-labelledby` when users pass ids.

2024-10-20 08:38 UTC, taiseiiiii commented
@108yen 
It's means, should I modify according to my [initial commit](https://github.com/yamada-ui/yamada-ui/pull/3147/commits/540b69b543ec563c6d674cb16e6a977f86388a5c)?

In addition, I gonna modify it that add the suffix to each id in order to avoid duplicate tabId and tabPanelId.
Is this thought correct?

2024-10-20 11:16 UTC, 108yen commented
@taiseiiiii 

When user passes id to `Tab`, we need to create `aria-labelledby` of `TabPanel` based on id passed by user.
Id of `TabPanel` should be the same.

I think it is necessary to suck the id up to the `Tabs` using `ref` or something and process it.

2024-10-21 06:00 UTC, taiseiiiii commented
@108yen 
I've just modified in order to handle each attribute according to user input.
Please review again.

2024-10-21 10:38 UTC, taiseiiiii commented
@taiseiiiii 
It works properly in my local environment.
Is it latest?

`tabs.stories.tsx`

```
export const basic: Story = () => {
  return (
    <Tabs>
      <Tab id="test">孫悟空</Tab>
      <Tab>ベジータ</Tab>
      <Tab>フリーザ</Tab>

      <TabPanel>
        <Text>クリリンのことか……クリリンのことかーーーっ！！！！！</Text>
      </TabPanel>
      <TabPanel>
        <Text>へっ！きたねぇ花火だ</Text>
      </TabPanel>
      <TabPanel>
        <Text>
          私の戦闘力は530000です。ですがもちろんフルパワーであなたと戦う気はありませんからご心配なく……
        </Text>
      </TabPanel>
    </Tabs>
  )
}
```

result

![スクリーンショット 2024-10-21 19 33 38](https://github.com/user-attachments/assets/44d3b3cb-95f4-4f3c-8289-ca62cedfb4ac)

I consider it proper, because "test" sets to aria-labelledby in first tabpanel component.

2024-10-21 11:03 UTC, 108yen submitted a review, later dismissed

2024-10-22 08:13 UTC, hirotomoyamada requested changes
If you set `TabList` or `TabPanels` to `children`, this logic is not supported.

It needs to be fundamentally rebuilt.

2024-10-22 13:34 UTC, taiseiiiii commented
@hirotomoyamada 
Thank you for your review.

I could only come up with the following way.
It seems to work properly.

If there are any other suitable ways to implement this, could you give me some tips?

Before
```
const tabPanelIds = cloneTabPanels.map(
  (panel, index) => panel.props.id ?? `${uuid}-${index}-tabpanel`,
)

const tabIds = cloneTabs.map(
  (tab, index) => tab.props.id ?? `${uuid}-${index}-tab`,
)
```

After
```
const tabPanelIds = (customTabPanels ? pickChildren(getValidChildren(customTabPanels.props.children), TabPanel) : cloneTabPanels).map(
  (panel, index) => panel.props.id ?? `${uuid}-${index}-tabpanel`,
)

const tabIds = (customTabList ? pickChildren(getValidChildren(customTabList.props.children), Tab) : cloneTabs).map(
  (tab, index) => tab.props.id ?? `${uuid}-${index}-tab`,
)
```

2024-10-22 14:46 UTC, hirotomoyamada commented
@taiseiiiii 

That is a bad approach from a performance standpoint.

To solve this problem, id must be transferred from the child to the parent.

2024-10-26 09:15 UTC, hirotomoyamada approved these changes

2024-10-26 09:19 UTC, merged