fix: improve form-control accessibility
yamada-ui/yamada-ui pull request #3180
Opened 2024-10-21 14:36 UTC by kaehehehe

Closes #3175

## Description

improve form-control accessibility

## Is this a breaking change (Yes/No):

No

2024-10-22 14:09 UTC, taiseiiiii requested changes
Please add changeset

2024-10-22 14:44 UTC, taiseiiiii commented
@kaehehehe 
I'm not confident in my understanding, so may I ask you some questions?

In what cases does `helperMessageId` become undefined?
When I checked in Storybook (components > forms > formcontrol > basic), a value is specified for `aria-labelledby` - is this expected behavior?

2024-10-24 13:25 UTC, kaehehehe commented
@taiseiiiii 
Typically, there is no behavior where `helperMessageId` becomes `undefined`.
I don't see aria-labelledby; which tag are you referring to?"

2024-10-25 03:50 UTC, taiseiiiii requested changes

2024-10-25 03:50 UTC, taiseiiiii commented on packages/components/transitions/.changeset/red-weeks-remember.md
> +"@yamada-ui/indicator": patch
Isn't "@yamada-ui/indicator"  unnecesary?

2024-10-26 03:45 UTC, kaehehehe commented on packages/components/transitions/.changeset/red-weeks-remember.md
> +"@yamada-ui/indicator": patch
Necessary. @taiseiiiii 
![스크린샷 2024-10-26 12 44 47](https://github.com/user-attachments/assets/33bc4782-919b-4248-8a36-e305c0c3227f)

2024-10-26 04:39 UTC, taiseiiiii approved these changes

2024-10-26 13:16 UTC, hirotomoyamada commented on packages/components/form-control/src/form-control.tsx
> +  errorMessage?: string
What is this necessary for? It doesn't seem necessary.

2024-10-26 13:16 UTC, hirotomoyamada commented on packages/components/form-control/src/form-control.tsx
> +  helperMessage?: string
What is this necessary for? It doesn't seem necessary.

2024-10-26 13:18 UTC, hirotomoyamada reviewed
Setting `aria-describedby` to `useFormControlProps` is too big in scope. You need to check each component one by one and investigate whether useless `aria-describedby` is given.

2024-11-02 08:18 UTC, kaehehehe commented
Currently, since useFormControlProps is used in various components, adding describedby will cause it to be added to components that do not need it. Therefore, I would like to close this PR for now and improve the structure of useFormControlProps first.

I will create an issue for further details.　@hirotomoyamada  @taiseiiiii

2024-11-02 08:18 UTC, closed without merging