Separation of UI and Logic in Component `Slider`
yamada-ui/yamada-ui pull request #3294
Opened 2024-10-31 01:53 UTC by EGASHIRAAkihide

Closes # 

## Description

Separate UI and Logic in `Slider.tsx` and move Logic to `use-slider.tsx`

## Current behavior (updates)

No Change

## New behavior

No Change

## Is this a breaking change (Yes/No):

No

## Additional Information

2024-10-31 02:01 UTC, EGASHIRAAkihide commented
### メモ：interface `SliderOptions` の配置に関して

このPRを作成するにあたり、他コンポーネントの実装を参考に分割いたしました。
`XXOptions` との名称で作成されているinterfaceのうち、`ripple`のみ、`use-ripple.tsx`に配置されておりました。
それ以外のcomponentに関しましては、基本的にUIファイルの方に型定義されているため、`ripple`のみロジックファイル側に`XXOptions` が格納されているか、理由が知りたいです。これは意図的に配置されているからでしょうか？

参考：`/packages/components/ripple/src/use-ripple.tsx`

In creating this PR, I referenced the implementation of other components and separated them accordingly. Among the interfaces created with the name `XXOptions`, only ripple is located in `use-ripple.tsx`. As for other components, their type definitions are generally in the UI files, so I would like to understand why only ripple has `XXOptions` stored on the logic file side. Was this placement intentional?

2024-11-04 09:03 UTC, kaehehehe reviewed
Thank you for the PR. @EGASHIRAAkihide 

Currently, we are planning to migrate the logic related to state and props to hooks in all components.

2024-11-04 09:13 UTC, kaehehehe requested changes

2024-11-04 09:13 UTC, kaehehehe commented on .changeset/chilly-ghosts-rhyme.md
> +"@yamada-ui/slider": major
Please change major to patch.

2024-11-04 09:35 UTC, kaehehehe commented on packages/components/slider/src/use-slider.tsx
I'm sorry, but could you change the extension of the hook from `.tsx` to `.tx`?

2024-11-05 02:52 UTC, kaehehehe approved these changes
Thanks for contributing!

2024-11-08 09:16 UTC, kaehehehe requested changes

2024-11-08 09:16 UTC, kaehehehe commented on .changeset/witty-rocks-search.md
> +"@yamada-ui/slider": patch
Sorry! 😢 The changeset is not needed for this PR, as it is related to refactoring. Please delete this file. @EGASHIRAAkihide

2024-11-11 15:38 UTC, hirotomoyamada commented
@EGASHIRAAkihide 

If this PR is incorporated first, conflicts will occur in other work, so close this PR.

Please submit this PR again after the other work is completed.

2024-11-11 15:38 UTC, closed without merging