Rewrite doc with named-export/import
yamada-ui/yamada-ui pull request #3295
Opened 2024-10-31 03:45 UTC by Shunii85

Closes #3165 

## Description
Rewrite with named-export/import instead of default-export/import

2024-10-31 05:41 UTC, aiirononeko submitted a review, later dismissed
LGTM!

2024-10-31 10:19 UTC, hirotomoyamada requested changes
The `customize-theme.ja.mdx`'s Lines 34, 35, 36, 523, and 524 have not been corrected.

The `customize-theme.mdx`'s Line 419 have not been corrected.

2024-10-31 10:20 UTC, hirotomoyamada commented on docs/contents/styled-system/theming/customize-theme.ja.mdx
Lines 34, 35, 36, 523, and 524 have not been corrected.

2024-10-31 10:21 UTC, hirotomoyamada commented on docs/contents/styled-system/theming/customize-theme.mdx
Line 419 have not been corrected.

2024-10-31 10:55 UTC, hirotomoyamada requested changes
- `docs/contents/styled-system/theming/component-styles.ja.mdx`
- `docs/contents/styled-system/theming/component-styles.mdx`
- `docs/contents/styled-system/animation.ja.mdx`
- `docs/contents/styled-system/animation.mdx`

These files also need to be modified.

2024-11-05 09:39 UTC, Shunii85 commented
@hirotomoyamada I have done! Please review.

2024-11-05 09:49 UTC, hirotomoyamada approved these changes

2024-11-05 10:41 UTC, merged