chore: rename left and right to start and end
yamada-ui/yamada-ui pull request #3320
Opened 2024-11-01 23:30 UTC by nathanlao

Closes #3283

## Description
Change `left` and `right` to `start` and `end` in the props and docs

props to be changed are marked `@deprecated` in v1.

## Current behavior (updates)

value of props were using `left*` and `right*`

## New behavior

value of props are now using `start*` and `end*`

## Is this a breaking change (Yes/No):

No

## Additional Information

2024-11-02 05:14 UTC, koralle commented
The file search and viewing of the documentation showed that it had been properly corrected.

2024-11-02 05:14 UTC, koralle approved these changes

2024-11-05 09:27 UTC, hirotomoyamada requested changes
Documentation should be created in a separate PR.This will reflect in the documentation when it is imported.

2024-11-06 00:29 UTC, nathanlao commented
@hirotomoyamada 

docs changeds had been done in #3346

2024-11-06 07:57 UTC, hirotomoyamada commented on packages/components/file-button/DOCS.json
This file is an automatically generated file. Please revert this file.

2024-11-06 07:57 UTC, hirotomoyamada commented on packages/components/button/DOCS.json
This file is an automatically generated file. Please revert this file.

2024-11-06 07:57 UTC, hirotomoyamada commented on packages/components/tag/DOCS.json
This file is an automatically generated file. Please revert this file.

2024-11-07 01:32 UTC, nathanlao commented
@hirotomoyamada 

Auto-generated files have been removed

2024-11-11 17:38 UTC, hirotomoyamada commented on packages/components/button/src/button.tsx
> +/* eslint-disable perfectionist/sort-objects */
Remove this line.

2024-11-11 17:38 UTC, hirotomoyamada commented on packages/components/button/src/button.tsx
> +/* eslint-disable perfectionist/sort-interfaces */
Remove this line.

2024-11-11 17:39 UTC, hirotomoyamada commented on packages/components/tag/src/tag.tsx
> +/* eslint-disable perfectionist/sort-interfaces */
Remove this line.

2024-11-12 01:10 UTC, nathanlao commented
@hirotomoyamada I have removed them, please re-review.

2024-11-12 08:14 UTC, hirotomoyamada submitted a review, later dismissed

2024-11-13 23:46 UTC, merged