refactor: updated NumberInput Component
yamada-ui/yamada-ui pull request #3367
Opened 2024-11-06 16:18 UTC by ogison

Closes #3366

## Description

Separation of UI and Logic in the NumberInput Component 

## Current behavior (updates)

## New behavior
No

## Additional Information

2024-11-07 13:47 UTC, 108yen requested changes
Target branch is wrong.
Change to `v2.0`.

2024-11-07 13:47 UTC, 108yen commented on .changeset/happy-pans-juggle.md
Please remove this file.
Changeset is not needed in this change. Because this change is just refactoring.

2024-11-07 13:53 UTC, ogison commented
I’ve updated the target branch to v2.0.

2024-11-07 13:59 UTC, ogison commented on .changeset/happy-pans-juggle.md
This has been addressed.
Please review it at your convenience.

2024-11-07 14:20 UTC, 108yen approved these changes

2024-11-11 15:19 UTC, hirotomoyamada approved these changes

2024-11-11 15:40 UTC, closed without merging