fix: change import of @yamada-ui/lucide in disclosure of Storybook to *Icon
yamada-ui/yamada-ui pull request #3390
Opened 2024-11-08 08:37 UTC by ChinoUkaegbu

Closes #3387

## Description

Changes import of @yamada-ui/lucide in disclosure of Storybook to *Icon.

## Current behavior (updates)

## New behavior

## Is this a breaking change (Yes/No):

No

## Additional Information

2024-11-08 09:08 UTC, illionillion requested changes
@ChinoUkaegbu 
Thank for creating PR!
Storybook is not a modification of the library itself, so there is no need to create a changeset.

2024-11-08 09:08 UTC, illionillion commented on .changeset/lemon-dryers-own.md
Plase remove this file.

2024-11-08 13:27 UTC, ChinoUkaegbu commented
Got it! I removed the file

2024-11-09 02:21 UTC, illionillion approved these changes
LGTM

2024-11-09 06:49 UTC, hirotomoyamada approved these changes

2024-11-09 08:01 UTC, merged