remove is prefix in props in the `Modal` package
yamada-ui/yamada-ui pull request #3397
Opened 2024-11-09 08:37 UTC by nathanlao

Closes #3302

## Description

package: @yamada-ui/modal

This PR is to remove is prefix in props:

`isOpen` to `open`
`isFullHeight` to `fullHeight`

## Is this a breaking change (Yes/No):

No

## Additional Information

2024-11-09 08:42 UTC, neginasu requested changes
Thanks for the PR!
The Quality test is down, please confirm!

2024-11-09 09:07 UTC, nathanlao commented
> Thanks for the PR! The Quality test is down, please confirm!

Thank you! I have made the change, please re-review :)

2024-11-09 14:55 UTC, neginasu requested changes
I’ve reviewed it! Please check.

2024-11-09 14:55 UTC, neginasu commented on packages/components/modal/src/drawer-content.tsx
> +    let { describedbyId, duration, isOpen, labelledbyId, open, onClose } =
Please define it as const instead of let.

2024-11-09 14:55 UTC, neginasu commented on packages/components/modal/src/drawer.tsx
> +    let {
Please define the variable as const, similar to how it's done with`packages/components/modal/src/drawer-content.tsx` .

2024-11-09 14:55 UTC, neginasu commented on packages/components/modal/src/modal.tsx
> +    let {
Please define the variable as const, similar to how it's done with`packages/components/modal/src/drawer-content.tsx` .

2024-11-10 03:37 UTC, neginasu submitted a review, later dismissed
Thanks for the confirmation!

LGTM🥳

2024-11-11 00:28 UTC, nathanlao commented
@neginasu Sorry! I realized there is one more [file](https://github.com/yamada-ui/yamada-ui/pull/3397/files#diff-e82cd10981b7450af44e699234828f0a3f79eed216537d28a8a388760f0ddd20) needs to be changed, would you be able to re-review it again when you have a moment? Thank you!

2024-11-11 01:17 UTC, neginasu submitted a review, later dismissed
Additional changes have been confirmed! 
LGTM🎉

2024-11-11 15:08 UTC, hirotomoyamada commented on packages/components/modal/src/drawer-content.tsx
> +/* eslint-disable perfectionist/sort-union-types */
Remove this line.

2024-11-11 15:08 UTC, hirotomoyamada commented on packages/components/modal/src/modal.tsx
> +/* eslint-disable perfectionist/sort-objects */
Remove this line.

2024-11-11 15:09 UTC, hirotomoyamada commented on packages/components/modal/src/modal.tsx
> +/* eslint-disable perfectionist/sort-interfaces */
Remove this line.

2024-11-12 01:16 UTC, nathanlao commented
@hirotomoyamada I have removed them, please re-review.

2024-11-12 08:12 UTC, hirotomoyamada approved these changes

2024-11-12 14:58 UTC, merged