feat: enhance keyboard interactions
yamada-ui/yamada-ui pull request #3472
Opened 2024-11-14 06:55 UTC by uraaaa24

Closes #3434

## Description

Implement key interactions of ArrowRight and ArrowLeft for PinInput

## Current behavior (updates)

## New behavior

## Is this a breaking change (Yes/No):

## Additional Information

2024-11-16 06:10 UTC, cidkumagai commented
@uraaaa24 
I think we need to write a test case for the keybord operation.

2024-11-16 08:01 UTC, odendayoko requested changes
@uraaaa24
Thank you for the implementation! I've made two comments, could you please check them?

As @cidkumagai has also mentioned, please add test code.

2024-11-17 04:23 UTC, uraaaa24 commented on packages/components/pin-input/src/pin-input.tsx
> +              focusInputField("prev", index)
You are correct, I will fix it that way!

2024-11-17 04:32 UTC, uraaaa24 commented on packages/components/pin-input/src/pin-input.tsx
> +        input.node.focus()
It certainly seems like a good idea to include `requestAnimationFrame`.
I will implement it that way!

2024-11-18 12:12 UTC, uraaaa24 commented
@cidkumagai @uraaaa24 
I have completed the corrections you pointed out.
Thank you for your understanding!

2024-11-18 15:54 UTC, odendayoko approved these changes
@uraaaa24 
Thanks! LGTM🧡

2024-11-18 19:59 UTC, hirotomoyamada approved these changes

2024-11-18 20:07 UTC, merged