feat(Pagination): remove `is` prefix in props
yamada-ui/yamada-ui pull request #3514
Opened 2024-11-15 11:00 UTC by kaehehehe

Closes #3492

## Description

Removing all is prefix from is*

## Is this a breaking change (Yes/No):

No

2024-11-15 13:30 UTC, 108yen requested changes

2024-11-15 13:30 UTC, 108yen commented on packages/components/pagination/src/pagination-item.tsx
> +   * @deprecated Use `active` instead.
Spacing one line apart.

2024-11-15 13:30 UTC, 108yen commented on packages/components/pagination/src/pagination-item.tsx
> +   * @deprecated Use `disabled` instead.
Spacing one line apart.

2024-11-15 13:30 UTC, 108yen commented on packages/components/pagination/src/use-pagination.ts
> +   * @deprecated Use `disabled` instead.
Spacing one line apart.

2024-11-15 13:30 UTC, 108yen commented on packages/components/pagination/src/pagination-item.tsx
`PaginationItem` is not exported in `index.ts`. So I think you can remove is prefix props.

2024-11-15 14:08 UTC, 108yen reviewed
No changeset.

2024-11-16 01:42 UTC, kaehehehe commented
> No changeset.

I determined that it was unnecessary because there were no changesets in the already merged PRs. @108yen 

- https://github.com/yamada-ui/yamada-ui/pull/3418
- https://github.com/yamada-ui/yamada-ui/pull/3420

2024-11-16 03:20 UTC, 108yen commented
@kaehehehe 
The change will not be published without changeset.

2024-11-16 07:02 UTC, kaehehehe commented on packages/components/pagination/src/pagination-item.tsx
Please read this. https://github.com/yamada-ui/yamada-ui/issues/3421

2024-11-16 07:05 UTC, kaehehehe commented on packages/components/pagination/src/pagination-item.tsx
> +   * @deprecated Use `active` instead.
Fixed.

2024-11-16 07:05 UTC, kaehehehe commented on packages/components/pagination/src/pagination-item.tsx
> +   * @deprecated Use `disabled` instead.
Fixed.

2024-11-16 07:05 UTC, kaehehehe commented on packages/components/pagination/src/use-pagination.ts
> +   * @deprecated Use `disabled` instead.
Fixed.

2024-11-16 07:11 UTC, kaehehehe commented
> @kaehehehe The change will not be published without changeset.

[This PR](https://github.com/yamada-ui/yamada-ui/pull/3491/files) was approved even though it doesn't have a changeset. Why is it that only my PR requires a changeset?

2024-11-16 07:30 UTC, 108yen commented
@kaehehehe 
I think the previous PR is wrong.

2024-11-16 14:07 UTC, 108yen approved these changes

2024-11-16 14:12 UTC, hirotomoyamada approved these changes

2024-11-17 11:54 UTC, merged