Replace AvatarIcon with LucideIcon.
yamada-ui/yamada-ui pull request #3526
Opened 2024-11-17 02:31 UTC by illionillion

Closes #3525  

## Description

Remove `AvatarIcon` in `Avatar` and use `@yamada-ui/lucide` icon.

## Current behavior (updates)

## New behavior

## Is this a breaking change (Yes/No):

## Additional Information

2024-11-17 02:53 UTC, kaehehehe submitted a review, later dismissed

2024-11-17 03:45 UTC, kaehehehe reviewed
@illionillion 
I'm sorry for asking this after the approval. I have a simple question. Why did you decide to use the Lucide icon directly in `avatar.tsx` instead of replacing the Icon in `avatar-icon.tsx`? I thought that using React Dev Tools would make it difficult to search for `AvatarIcon` since it wouldn't have a displayName. Is that not a concern?

2024-11-17 03:54 UTC, illionillion commented
> @illionillion I'm sorry for asking this after the approval. I have a simple question. Why did you decide to use the Lucide icon directly in `avatar.tsx` instead of replacing the Icon in `avatar-icon.tsx`? I thought that using React Dev Tools would make it difficult to search for `AvatarIcon` since it wouldn't have a displayName. Is that not a concern?

@kaehehehe 
Because Mr. Yamada said he would delete it.
The `v2` modification will apply `displayName` to all the icons in `@yamada-ui/lucide`, so that should be no problem.

2024-11-17 11:44 UTC, hirotomoyamada requested changes
Insert `@yamada-ui/lucide` to `package.json`.

2024-11-18 03:16 UTC, illionillion commented
@hirotomoyamada 
I fixed `package.json`.
Please review again.

2024-11-18 12:49 UTC, kaehehehe commented on packages/components/avatar/src/avatar.tsx
> +import { UserRoundIcon } from "../../lucide/src"
I think you need to fix this line.
```suggestion
import { UserRoundIcon } from "@yamada-ui/lucide"
```

2024-11-18 12:59 UTC, illionillion commented on packages/components/avatar/src/avatar.tsx
> +import { UserRoundIcon } from "../../lucide/src"
FIxed.

2024-11-18 13:27 UTC, kaehehehe submitted a review, later dismissed
LGTM!

2024-11-25 01:13 UTC, hirotomoyamada approved these changes

2024-11-25 01:33 UTC, merged