fix: fix `Icon` to `FontAwesomeIcon`
yamada-ui/yamada-ui pull request #3586
Opened 2024-11-22 06:59 UTC by illionillion

Closes #3585 

## Description

## Current behavior (updates)

## New behavior

## Is this a breaking change (Yes/No):

## Additional Information

2024-11-24 16:07 UTC, odendayoko requested changes
@illionillion 
Please update the import statement in the following files:

- docs/contents/components/media-and-icons/icon/index.ja.mdx
- docs/contents/components/media-and-icons/icon/index.mdx

Change line 81 in both files from:
```diff ts
- import { Icon as FontAwesomeIcon } from "@yamada-ui/fontawesome"
+ import { FontAwesomeIcon } from "@yamada-ui/fontawesome"
```

2024-11-25 13:33 UTC, illionillion commented
> @illionillion Please update the import statement in the following files:
> 
> * docs/contents/components/media-and-icons/icon/index.ja.mdx
> * docs/contents/components/media-and-icons/icon/index.mdx
> 
> Change line 81 in both files from:
> 
> ```diff
> - import { Icon as FontAwesomeIcon } from "@yamada-ui/fontawesome"
> + import { FontAwesomeIcon } from "@yamada-ui/fontawesome"
> ```

@odendayoko  Thanks!
Please review again.

2024-11-25 15:07 UTC, odendayoko approved these changes
@illionillion 
Thanks!! LGTM🧡

2024-11-26 00:55 UTC, hirotomoyamada approved these changes

2024-11-26 01:10 UTC, merged