Replaced `For` in `CloseButton` documentation
yamada-ui/yamada-ui pull request #3836
Opened 2024-12-08 03:16 UTC by illionillion

Closes #3782  

## Description

<img width="711" alt="image" src="https://github.com/user-attachments/assets/85d7c04e-2268-46d8-bf28-7261d1540320">

## Current behavior (updates)

## New behavior

## Is this a breaking change (Yes/No):

## Additional Information

2024-12-08 06:04 UTC, hirotomoyamada requested changes
Please correct as #3834.

2024-12-08 06:27 UTC, illionillion commented
@hirotomoyamada 
I fixed it. Plase review again!

2024-12-09 07:53 UTC, hirotomoyamada approved these changes

2024-12-09 15:25 UTC, hirotomoyamada approved these changes

2024-12-09 15:51 UTC, merged