Use <For/> in `ColorPicker` documentation
yamada-ui/yamada-ui pull request #3842
Opened 2024-12-09 06:43 UTC by kaehehehe

Closes #3744

## Description

Fixed the repetition part in the `ColorPicker` documentation to use the `For` component.

## Is this a breaking change (Yes/No):

No

2024-12-09 08:52 UTC, 108yen submitted a review, later dismissed

2024-12-09 15:24 UTC, hirotomoyamada commented on docs/contents/components/forms/color-picker/index.ja.mdx
> +    each={[
Change `each={["outline", "filled", "flushed"]}`.

2024-12-09 15:24 UTC, hirotomoyamada commented on docs/contents/components/forms/color-picker/index.ja.mdx
> +    each={[
Change `each={["outline", "filled", "flushed"]}`.

2024-12-09 15:24 UTC, hirotomoyamada commented on docs/contents/components/forms/color-picker/index.mdx
Please modify it as you did for the Japanese page.

2024-12-10 02:02 UTC, kaehehehe commented on docs/contents/components/forms/color-picker/index.ja.mdx
> +    each={[
Fixed.

2024-12-10 02:02 UTC, kaehehehe commented on docs/contents/components/forms/color-picker/index.ja.mdx
> +    each={[
Fixed.

2024-12-10 02:02 UTC, kaehehehe commented on docs/contents/components/forms/color-picker/index.ja.mdx
> +    each={[
Fixed.

2024-12-24 10:24 UTC, odendayoko commented on docs/contents/components/forms/color-picker/index.ja.mdx
> +    each={[
@kaehehehe 
Add `unstyled` to the array.

2024-12-24 10:28 UTC, odendayoko requested changes
@kaehehehe 
Please make similar modifications.
```diff
- <For each={["outline", "filled", "flushed"]}>
+ <For each={["outline", "filled", "flushed", "unstyled"]}>
```

- `docs/contents/components/forms/color-picker/index.ja.mdx` L31
- `docs/contents/components/forms/color-picker/index.mdx` L33

2024-12-25 04:17 UTC, kaehehehe commented
> @kaehehehe Please make similar modifications.
> 
> ```diff
> - <For each={["outline", "filled", "flushed"]}>
> + <For each={["outline", "filled", "flushed", "unstyled"]}>
> ```
> 
> * `docs/contents/components/forms/color-picker/index.ja.mdx` L31
> * `docs/contents/components/forms/color-picker/index.mdx` L33

@odendayoko 
Thank you for catching this mistake. :)

2024-12-25 11:23 UTC, odendayoko approved these changes
@kaehehehe 
Thanks!! LGTM🧡

2024-12-26 00:02 UTC, hirotomoyamada approved these changes

2024-12-26 00:59 UTC, merged