Use <For/> in `Blockquote` documentation
yamada-ui/yamada-ui pull request #3874
Opened 2024-12-10 09:31 UTC by kaehehehe

Closes #3703

## Description

Fixed the repetition part in the `Blockquote` documentation to use the `For` component.

## Is this a breaking change (Yes/No):

No

2024-12-10 11:09 UTC, 108yen requested changes

2024-12-10 11:09 UTC, 108yen commented on docs/contents/components/typography/blockquote/index.ja.mdx
> +        colorScheme: "",
This can be deleted.

2024-12-10 11:09 UTC, 108yen commented on docs/contents/components/typography/blockquote/index.mdx
> +        colorScheme: "",
This can be deleted.

2024-12-11 02:16 UTC, kaehehehe commented on docs/contents/components/typography/blockquote/index.ja.mdx
> +        colorScheme: "",
Fixed.

2024-12-11 02:43 UTC, 108yen approved these changes

2024-12-11 09:04 UTC, hirotomoyamada approved these changes

2024-12-11 09:25 UTC, merged