Replace `StatIcon` with `TriangleIcon` from `@yamada-ui/lucide`
yamada-ui/yamada-ui pull request #3947
Opened 2024-12-10 14:33 UTC by odendayoko

Closes #3532 

## Description
Replace `StatIcon` with `TriangleIcon` from `@yamada-ui/lucide`.
The theme was also modified to match the current icon look and feel.

## Current behavior (updates)

<img width="226" alt="Stat_-_Yamada_UI" src="https://github.com/user-attachments/assets/e3f38e2f-5361-4280-b067-c6b1c4c8473d">

## New behavior

<img width="227" alt="Stat_-_Yamada_UI" src="https://github.com/user-attachments/assets/4d8fd21d-989a-4b0f-92ea-646b1c08b86d">

## Is this a breaking change (Yes/No):
No

2024-12-11 06:28 UTC, 108yen requested changes

2024-12-11 06:28 UTC, 108yen commented on packages/components/stat/src/stat-icon.tsx
> +    }
Please change order.
```tsx
    const css: CSSUIObject = {
      color,
      fill: color,
      transform: type === "decrease" ? "rotate(180deg)" : undefined,
      ...styles.icon,
    }
```

2024-12-11 06:28 UTC, 108yen commented on packages/components/stat/src/stat-icon.tsx
>          viewBox="0 0 24 24"
`viewBox` prop is unnecessary.

2024-12-14 06:48 UTC, odendayoko commented
@108yen 
Thanks!! Please re-review as corrected🙇‍♀️
https://github.com/yamada-ui/yamada-ui/pull/3947/commits/aa61704c1c9594b0f047cd48b0774558d91fefbe

2024-12-14 07:23 UTC, 108yen approved these changes

2024-12-15 16:22 UTC, hirotomoyamada approved these changes

2024-12-15 16:23 UTC, merged