docs: use For
yamada-ui/yamada-ui pull request #4076
Opened 2024-12-14 03:36 UTC by YoshimasaAsada

Closes #3772

## Description

Fixed the repetition part in the Tooltip documentation to use the For component.

## Current behavior (updates)

## New behavior

## Is this a breaking change (Yes/No):

No

## Additional Information

2024-12-14 11:40 UTC, Shunii85 requested changes
@YoshimasaAsada 
Thanks for the PR ! It looks good to me for the behaviors, but I would like you to fix tooltip's text dynamically

For example ... (placement title)
```ts
<Text w="fit-content">Open {placement.split("-").reduce((prev, next) => prev + " " + next)} Tooltip</Text>
```

2024-12-14 11:40 UTC, Shunii85 commented on docs/contents/components/overlay/tooltip/index.ja.mdx
> +        <Text w="fit-content">Open right end Tooltip</Text>
Please fix tooltip's text dynamically!

2024-12-14 11:40 UTC, Shunii85 commented on docs/contents/components/overlay/tooltip/index.ja.mdx
> +        <Text w="fit-content">Open right end Tooltip</Text>
Please fix tooltip's text dynamically!

2024-12-14 11:40 UTC, Shunii85 commented on docs/contents/components/overlay/tooltip/index.mdx
> +        <Text w="fit-content">Open right end Tooltip</Text>
Please fix tooltip's text dynamically!

2024-12-14 11:40 UTC, Shunii85 commented on docs/contents/components/overlay/tooltip/index.mdx
> +        <Text w="fit-content">Open right end Tooltip</Text>
Please fix tooltip's text dynamically!

2024-12-15 22:51 UTC, YoshimasaAsada commented
I have made the changes. Please review them.

2024-12-19 13:13 UTC, Shunii85 approved these changes
@YoshimasaAsada 
I'm sorry I'm late for re-review.
LGTM!!

2024-12-19 20:59 UTC, hirotomoyamada approved these changes

2024-12-19 21:24 UTC, merged