docs: use For
yamada-ui/yamada-ui pull request #4077
Opened 2024-12-14 04:14 UTC by shunji-muto

Closes # 

## Description
Use the `<For />` component in `<Float />` docs

## Current behavior (updates)

## New behavior

## Is this a breaking change (Yes/No):
No

## Additional Information

2024-12-16 00:33 UTC, koralle requested changes
Thank you for the PR.

It would be better to replace this part with `<For />`.

```diff
### 表示位置を変更する

表示位置を変更する場合は、`placement`に`start-start`や`end-center`などを指定します。

```tsx functional=true
- const placements = [
-   "start-start",
-   "start-center",
-   "start-end",
-   "center-start",
-   "center-center",
-   "center-end",
-   "end-start",
-   "end-center",
-   "end-end",
- ] as const
- return (
-   <Grid w="fit-content" gap="md" p="md" templateColumns="repeat(3, 1fr)">
-     {placements.map((placement) => (
-       <GridItem
-         key={placement}
-         bg={["blackAlpha.50", "whiteAlpha.50"]}
-         boxSize="3xs"
-         position="relative"
-       >
-         <Float placement={placement}>
-           <Center
-             bg="primary"
-             color="white"
-             fontSize="sm"
-             px="1.5"
-             rounded="md"
-           >
-             New
-           </Center>
-         </Float>
-       </GridItem>
-     ))}
-   </Grid>
- )
+ return (
+   <Grid gap="md" p="md" templateColumns="repeat(3, 1fr)">
+     <For each={[
+       "start-start",
+       "start-center",
+       "start-end",
+       "center-start",
+       "center-center",
+       "center-end",
+       "end-start",
+       "end-center",
+       "end-end",
+     ]}>
+       {(placement, index) => (
+         <GridItem
+           key={index}
+           bg={["blackAlpha.50", "whiteAlpha.50"]}
+           boxSize="3xs"
+           position="relative"
+         >
+           <Float placement={placement}>
+             <Center
+               bg="primary"
+               color="white"
+               fontSize="sm"
+               px="1.5"
+               rounded="md"
+             >
+               New
+             </Center>
+           </Float>
+         </GridItem>
+       )}
+     </For>
+   </Grid>
+ )
```

2024-12-22 02:03 UTC, shunji-muto commented on docs/contents/components/layouts/float/index.ja.mdx
> +    {(variant, index) => (
Thank you for the review.

I modified based on the review comments.

2024-12-22 02:03 UTC, shunji-muto commented on docs/contents/components/layouts/float/index.mdx
> +    {(variant, index) => (
Thank you for the review.

I modified based on the review comments

2024-12-27 06:40 UTC, koralle approved these changes
Thank you!

2024-12-27 07:52 UTC, hirotomoyamada approved these changes

2024-12-27 08:29 UTC, merged