Use <For /> in Card documentation
yamada-ui/yamada-ui pull request #4079
Opened 2024-12-14 11:32 UTC by yu-yaba

Closes #3746  

## Description
Fixed the repetition part in the `card` documentation to use the `For` component.

## Is this a breaking change (Yes/No):
No

2024-12-19 11:20 UTC, illionillion requested changes
@yu-yaba Thank for PR!

It is cleaner to correct as per the review.

2024-12-19 11:20 UTC, illionillion commented on docs/contents/components/data-display/card/index.ja.mdx
> +    {({ size }, index) => (
```suggestion
    each={["sm", "md", "normal", "lg"]}
  >
    {(size, index) => (
```

2024-12-19 11:20 UTC, illionillion commented on docs/contents/components/data-display/card/index.ja.mdx
> +      <Card key={index} variant={item.variant}>
```suggestion
  <For
    each={[
      "elevated",
      "outline",
      "subtle",
      "solid",
    ]}
  >
    {(variant, index) => (
      <Card key={index} variant={variant}>
```

2024-12-19 11:20 UTC, illionillion commented on docs/contents/components/data-display/card/index.mdx
@yu-yaba 

Please fix it the same way as the Japanese version.

2024-12-20 01:57 UTC, yu-yaba commented
@illionillion 
Thanks! 
I fixed it. Please review them.

f4ba1e2a0d8d8290727b0a8550f73f9f3cc5d875

2024-12-20 02:41 UTC, illionillion approved these changes

2024-12-20 23:52 UTC, hirotomoyamada approved these changes
Thanks!

2024-12-21 01:02 UTC, merged