Use <For /> in Status documentation
yamada-ui/yamada-ui pull request #4102
Opened 2024-12-16 11:27 UTC by HT0323

Closes https://github.com/yamada-ui/yamada-ui/issues/3774

## Description
Use the `<For />` component in `Status` docs

## Current behavior (updates)

## New behavior

## Is this a breaking change (Yes/No):
No

## Additional Information

2024-12-17 12:08 UTC, Shunii85 requested changes
@HT0323 Thanks for the PR !!
We took mistakes, this is why there are some request changes. I'm sorry!

2024-12-17 12:08 UTC, Shunii85 commented on docs/contents/components/feedback/status/index.mdx
> +  </For>
You don't have to use `For` component. Sorry!! Please revert them.

2024-12-18 09:32 UTC, HT0323 commented
@Shunii85 
I've fixed it, please leave a review.

2024-12-21 00:57 UTC, Shunii85 approved these changes
@HT0323 
Thanks for the changes ! 
I'm sorry I'm late for re-review. LGTM !!

2024-12-21 02:52 UTC, hirotomoyamada approved these changes

2024-12-21 03:01 UTC, merged