refactor: move styles to theme for form autocomplete
yamada-ui/yamada-ui pull request #4250
Opened 2024-12-29 13:49 UTC by chida09

Closes https://github.com/yamada-ui/yamada-ui/issues/3876

## Description

## Current behavior (updates)

## New behavior

## Is this a breaking change (Yes/No):

## Additional Information

2024-12-30 08:32 UTC, odendayoko commented
@chida09 @hirotomoyamada 
Thanks!!
I don't think the PR fix itself is a problem, but the `Autocomplete` width does not seem to spread to the full width in `v2.0`.
- `v1.7`
<img width="1377" alt="Components___Forms___Autocomplete_-_Basic_⋅_Storybook" src="https://github.com/user-attachments/assets/7b7aba90-9058-4905-b80c-7d6839da593c" />

- `v2.0`
<img width="1379" alt="Components___Autocomplete_-_Basic_⋅_Storybook" src="https://github.com/user-attachments/assets/30353fa8-a469-4278-a347-99ca97192854" />


I confirmed that the style of `styles.container` applied to the class name `ui-autocomplete` has been changed as follows:
```ts
//  v1.7
container: {
  h: "fit-content",
  w: "100%",
},

//  v2.0
container: {
  display: "flex"
  h: "fit-content"
  position: "relative"
  w: "100%"
  width: "100%"
}

```
Can I approve this PR since it has been happening before I made this correction?Also, do you want to give this bug to Issue?

2025-01-06 07:27 UTC, hirotomoyamada commented
@chida09 @odendayoko 

Hi, no, you can't.We do not expect any style changes as we move from `v1.0` to `v2.0`.

2025-01-06 13:29 UTC, odendayoko requested changes
@chida09 
Try to resolve the conflict and confirm that the style is the same as in `v1.0`.

2025-01-06 14:12 UTC, chida09 commented
Since the issue was not resolved, I will look into it a bit more.

2025-01-20 10:54 UTC, hirotomoyamada submitted a review, later dismissed

2025-02-20 09:22 UTC, hirotomoyamada commented
I will fix it together with another work, so I will close it.

2025-02-20 09:22 UTC, closed without merging