fix: automatic resizing of textArea
yamada-ui/yamada-ui pull request #828
Opened 2024-02-26 13:19 UTC by taku10101

Closes #827

## Description

Fixed a bug that autosize did not work when reset was executed when running Textarea component on React Hook Form.

## Current behavior (updates)

Running Textarea component on React Hook Form, autosize does not work when reset is executed

## New behavior

Running Textarea component on React Hook Form, autosize works when reset is executed

## Is this a breaking change (Yes/No):
No

## Additional Information

2024-02-26 15:53 UTC, hirotomoyamada commented
@taku10101 

Hi, thanks for the PR.

Consider alternatives such as `useUpdateEffect` instead of `useSafeLayoutEffect`.
The reason is that `resizeTextarea` is executed twice the first time.

Good luck :)

2024-02-29 13:33 UTC, setodeve requested changes

2024-02-29 13:33 UTC, setodeve commented on .changeset/ten-spiders-report.md
Please delete this file , 
because of that changeset file already exists as `rare-dragons-drop.md`

2024-02-29 13:33 UTC, setodeve commented on packages/components/textarea/src/textarea.tsx
> +  //textが空の場合はautosize
Please write in English.

2024-02-29 13:47 UTC, 108yen commented on packages/components/textarea/src/textarea.tsx
> +  //textが空の場合はautosize
@taku10101 
Do not leave a comment.

2024-02-29 13:51 UTC, 108yen requested changes

2024-02-29 13:51 UTC, 108yen commented on packages/components/textarea/src/textarea.tsx
> +  }
I think this is good.
```tsx
useUpdateEffect(() => {
    if (!isBrowser || !autosize) return
    resizeTextarea()
  }, [textareaRef.current?.value])
```

2024-03-01 05:54 UTC, 108yen reviewed
@hirotomoyamada 
Since `useEffect`(and `useUpdateEffect`) cannot detect changes in ref, it is implemented in conditional statements. 
Is there a better way to implement it? Is this OK?

2024-03-01 05:54 UTC, 108yen commented on packages/components/textarea/src/textarea.tsx
> +    textareaRef.current.style.height !== "0px"
In what circumstances is this conditional statement necessary?

2024-03-01 14:49 UTC, hirotomoyamada commented
@108yen 

Hi, even if you assign a `ref.current.value` to a variable and make it a primitive type, `useEffect` or `useUpdateEffect` will be executed.

2024-03-04 14:33 UTC, closed without merging