test(highlight): enhance test coverage
yamada-ui/yamada-ui pull request #925
Opened 2024-03-06 05:48 UTC by txxxxc

Closes #785 

## Description
Enhance test coverage for components with less than 80% coverage to meet or exceed 80%.

## Is this a breaking change (Yes/No):
No

## Additional Information
This is my first pull request for OSS, so if you have any suggestions for improvement, I would appreciate it.

2024-03-06 18:54 UTC, taroj1205 requested changes
Hi txxxxc,
Thank you for your PR.
Please run
```
pnpm run format
```
in your terminal to format your code with prettier.

2024-03-06 23:08 UTC, txxxxc commented on packages/components/highlight/tests/highlight.test.tsx
> +      <Highlight query="Highlight" markProps={{ borderRadius: '12px' }}>
resolved in https://github.com/yamada-ui/yamada-ui/pull/925/commits/8230096307394b9b67ce73e539cef823c364362d

2024-03-06 23:12 UTC, txxxxc commented
Thank you for reviewing. Could you please check the PR again?

2024-03-07 01:11 UTC, taroj1205 approved these changes
Approved.

2024-03-07 08:50 UTC, merged

2024-03-07 08:50 UTC, hirotomoyamada commented
Thanks!